### PR TITLE
LPS-111515 Remove bootdelegation hacks needed for the GA.

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
@vicnate5 really not expecting anything to fail here unless the portal doesn't start up, only functional tests are failing.

**Comment by vicnate5** [comment]
@Preston-Crary Taking a look, the failures here are look like obvious bugs

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@Preston-Crary Failures are unique and related to this change

Steps to Reproduce:
1. Navigate to site Blogs admin portlet or Message Boards admin portlet

**Blogs:**
Full log: https://testray.liferay.com/reports/production/logs/test-1-18/1585946487104/test-portal-acceptance-pullrequest(master)/3153/functional-tomcat90-mysql57-jdk8/3/0/liferay-log.txt.gz
```
ERROR [http-nio-8080-exec-4][LiferayMethodExceptionEventHandler:54] Unable to execute method processMax {exception=com.liferay.portal.kernel.portlet.PortletContainerException: javax.servlet.ServletException: java.lang.NoClassDefFoundError: com.liferay.expando.kernel.model.ExpandoBridge cannot be found by com.liferay.blogs.api_6.3.0, className=com.liferay.portal.layoutconfiguration.util.velocity.TemplateProcessor}
com.liferay.portal.kernel.portlet.PortletContainerException: javax.servlet.ServletException: java.lang.NoClassDefFoundError: com.liferay.expando.kernel.model.ExpandoBridge cannot be found by com.liferay.blogs.api_6.3.0
	at com.liferay.portlet.internal.PortletContainerImpl._preserveGroupIds(PortletContainerImpl.java:428)
	at com.liferay.portlet.internal.PortletContainerImpl.render(PortletContainerImpl.java:211)
	at com.liferay.portlet.SecurityPortletContainerWrapper.render(SecurityPortletContainerWrapper.java:145)
	at com.liferay.portlet.RestrictPortletContainerWrapper.lambda$render$0(RestrictPortletContainerWrapper.java:124)
	at com.liferay.portlet.RestrictPortletContainerWrapper._render(RestrictPortletContainerWrapper.java:185)
	at com.liferay.portlet.RestrictPortletContainerWrapper.render(RestrictPortletContainerWrapper.java:122)
	at com.liferay.portal.kernel.portlet.PortletContainerUtil.render(PortletContainerUtil.java:214)
	at com.liferay.portal.layoutconfiguration.util.velocity.TemplateProcessor.processMax(TemplateProcessor.java:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:389)
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:378)
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:270)
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:262)
	at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:342)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:336)
	at org.apache.velocity.Template.merge(Template.java:328)
	at org.apache.velocity.Template.merge(Template.java:235)
	at com.liferay.portal.template.velocity.internal.VelocityTemplate.processTemplate(VelocityTemplate.java:116)
	at com.liferay.portal.template.BaseTemplate.processTemplate(BaseTemplate.java:128)
	at com.liferay.portal.layoutconfiguration.util.RuntimePageImpl.doProcessTemplate(RuntimePageImpl.java:413)
	at com.liferay.portal.layoutconfiguration.util.RuntimePageImpl.doDispatch(RuntimePageImpl.java:327)
	at com.liferay.portal.layoutconfiguration.util.RuntimePageImpl.getProcessedTemplate(RuntimePageImpl.java:78)
	at com.liferay.portal.kernel.layoutconfiguration.util.RuntimePageUtil.getProcessedTemplate(RuntimePageUtil.java:37)
	at com.liferay.application.list.taglib.display.context.logic.PanelAppContentHelper.writeContent(PanelAppContentHelper.java:86)
	at org.apache.jsp.application_005fcontent.page_jsp._jspService(page_jsp.java:161)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
```

**Message Boards**
Full log: https://testray.liferay.com/reports/production/logs/test-1-18/1585946487104/test-portal-acceptance-pullrequest(master)/3153/functional-tomcat90-mysql57-jdk8/3/0/liferay-log.txt.gz
```
ERROR [http-nio-8080-exec-9][IncludeTag:128] Current URL /web/guest/message-boards generates exception: com.liferay.portal.kernel.portlet.PortletContainerException: javax.servlet.ServletException: java.lang.NoClassDefFoundError: com.liferay.expando.kernel.model.ExpandoBridge cannot be found by com.liferay.message.boards.api_6.2.0
java.lang.NoClassDefFoundError: com.liferay.expando.kernel.model.ExpandoBridge cannot be found by com.liferay.message.boards.api_6.2.0
	at com.liferay.message.boards.model.impl.MBThreadModelImpl.lambda$_getProxyProviderFunction$0(MBThreadModelImpl.java:325)
	at com.liferay.message.boards.model.impl.MBThreadModelImpl.toEscapedModel(MBThreadModelImpl.java:1150)
	at com.liferay.message.boards.model.impl.MBThreadModelImpl.toEscapedModel(MBThreadModelImpl.java:71)
	at com.liferay.taglib.ui.SearchContainerRowTag.processRow(SearchContainerRowTag.java:292)
	at com.liferay.taglib.ui.SearchContainerRowTag.doStartTag(SearchContainerRowTag.java:141)
	at org.apache.jsp.message_005fboards.view_jsp._jspService(view_jsp.java:3279)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:373)
	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:385)
	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153)
	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62)
	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120)
	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48)
	at com.liferay.portlet.internal.PortletRequestDispatcherImpl.dispatch(PortletRequestDispatcherImpl.java:291)
	at com.liferay.portlet.internal.PortletRequestDispatcherImpl.include(PortletRequestDispatcherImpl.java:123)
```

**Comment by vicnate5** [comment]
Also affecting OAuth2
https://testray.liferay.com/reports/production/logs/test-1-18/1585946487104/test-portal-acceptance-pullrequest(master)/3153/functional-tomcat90-mysql57-jdk8/5/0/liferay-log.txt.gz

**Comment by Preston-Crary** [comment]
Alright, thanks!

**Pull request closed without merging**
