### PR TITLE
LPS-72193 Create new friendly URL entry localisations instead of updating existing to avoid confusion

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
Hey @shuyangzhou ,

This implementation seems to be clearer. The main idea is that we should keep all old Friendly URLs (as we discussed once in Skype) in order to maintain SEO results since old URLs could be already indexed by search engines. addFriendlyURLEntry() method does just that, it basically adds new FriendlyURLEntry and updates the mapping(we use FriendlyURLMapping entity to store our current URL, instead of “main” field as it was done before).
In case when URL already exists in the DB for the same type of entity(same classNameId), but with different classPK, we are trying to create a unique title for it(like we do with Layouts - if “/page” already exists we do “/page-1” etc.).
Also we have getUniqueUrlTitle() method which should be used in modules (there is an example in Blogs) to get unique URL title for the entity. If someone doesn’t use this method and passes existing URL title DuplicateFriendlyURLEntryException is thrown.

Thanks.

/cc @JorgeFerrer

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
Hi @pavel-savinov,

I think we should step back a bit and talk about how we want the API to work.  It's been several months since I've looked at this so I'm a little lost on the requirements.  Here's the complete list of requirements as I remember them:

1. We need a way to look up a friendly URLs for assets like this: `groupId, classNameId, classPK[, languageId] -> friendlyURL`.  Language ID is optional.
2. We need a way to look up assets like this: `classNameId, friendlyURL -> classPK`.
3. Friendly URLs must be unique per `groupId, classNameId` and should never be removed unless the asset or group is removed.
4. Have a way to list all the translated Friendly URLs for the asset.
5. A way to create new friendly URLs for an existing asset while keeping the old ones.

Are there any other requirements?  Please be as specific as possible.

**Comment by pavel-savinov** [comment]
Hi @Preston-Crary 
Basically that is it. As I mentioned, it is already in use, we just introduced localisation stuff.

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
Hi @pavel-savinov,

the structure of the tables still seems off to @shuyangzhou and I.  In your code you always **add** FriendlyURLEntitys but then **add and/or update** FriendlyURLEntityLocalizations.  There is also dead code in the FriendlyURLEntityLocalServiceImpl.updateFriendlyURLEntryLocalizations method because the call to validate will prevent some of the code for ever happening (there is only one usage).

Please carefully define your table structure to optimize for the use cases we've talked about above.

I think a good database design will have a one-to-one relationship between the asset (BlogsEntry) and the FriendlyURLEntry, this will also mean the FriendlyURLEntryMapping table will need re-looked at.  I think it will not be possible to have a good solution and use the localized-entity in the service.xml.

When you have a good table structure ready you can comment here and I'll double check that it makes sense for the use case above.

**Pull request closed without merging**
