### PR TITLE
LPS-98197 get dlFileEntry from database nor imported fileEntry

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
Hey @Preston-Crary and @4lejandrito 

I changed the code to delete the fetch and simplify as you said on https://github.com/Preston-Crary/liferay-portal/pull/828#discussion_r310715318

Check if ok.

now the only failing test is one on master (DLFileEntryIndexerIndexedFieldsTest.testIndexedFields) and it is already reported (https://issues.liferay.com/browse/LPS-99198) 

If you send Brian, remember this must not be backported, and the task it's not completed yet.

Thank you for all!

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
Hi @AliciaGarciaGarcia,

the test https://github.com/Preston-Crary/liferay-portal/pull/829#issuecomment-518646801 is failing because of your commit messages in 0c4a2ab297e37d18f55cc3baa226d0b10b477055, 5faad97febc675fda2e7d82adf0cb1e72dfee7b4 and 4486cc04161b2d71a2dbe68d2aee9a07330bfcac.

Please cherry-pick the original commits that were reverted and resend with your change from #565 

Thanks!

**Pull request closed without merging**
