### PR TITLE
LPS-69532 Change SynchronousDestinationTestCallback to supports workflow

### PR DESCRIPTION
**Pull request by inacionery**
Hi @Preston-Crary,

I'm creating an integration test for the issue https://issues.liferay.com/browse/LPS-69532, but I'm facing "java.lang.OutOfMemoryError: Java heap space" on CI. I can't reproduce this locally.

Could you please help me with it?

Thanks advanced!

### CODE REVIEW

**Comment by inacionery** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
@inacionery I found the source of the OOM, I'll send a pull for the cause and link it here when it's ready.  

Also there's a problem with your test, there's a warning being printed because you're not connected to a mail server, either use / create a test one or use a CaptureAppender to assert the warning - there's some example of that in VerifyPropertiesTest.

**Comment by inacionery** [comment]
Awesome!!!!  Thanks a lot!!!! 

/cc @marcellustavares @vicnate5

**Comment by marcellustavares** [comment]
wow, thanks a lot @Preston-Crary

**Comment by Preston-Crary** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/3679

**Pull request closed without merging**
