### PR TITLE
LPS-130162 - Create display renderers for Organization

### PR DESCRIPTION
**Pull request by ctang3**
https://issues.liferay.com/browse/LPS-130162

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
@ctang3 please run "ant clean deploy" in portal-kernel and push the packageinfo.

**Comment by ctang3** [comment]
@Preston-Crary just pushed, thanks

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by ctang3** [comment]
ci:forward

**Comment by ctang3** [comment]
ci:forward

**Comment by xbrianlee** [comment]
Manually forwarded to https://github.com/brianchandotcom/liferay-portal/pull/100986

**Comment by xbrianlee** [comment]
ci:close

**Comment by xbrianlee** [comment]
This PR wasn't forwarded properly. Re-forwarding in https://github.com/xbrianlee/liferay-portal/pull/592.

**Pull request closed without merging**
