### PR TITLE
LPS-86298 Improving thread safety

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @Preston-Crary,

We want to contribute repository capabilities from outside of the core.

We want this for the parent ticket [LPS-84799](https://issues.liferay.com/browse/LPS-84799). The next step would be implementing a custom capability in a separate module (that would be managed by LiferayDynamicCapability) to manage file versions and allow customization from third party developers (limit the number of file versions stored for example).

We thought using capabilities would be the best way to proceed. Our plan was to get the _infrastructure_ for it (i.e. this pull request) merged and then develop the solution on top of it.

I've protected the 2 critical sections to make it thread safe but it would be great if you could give us a hand to make it better if possible.

Thanks a lot!

@adolfopa

Please
@adolfopa

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/6959

I still have a incomplete picture of what the goal is without any usage.

Our team's style of development is to make small changes that make sense on their own preparing for bigger changes and then when it's easier add new API with some usages so we have a more complete picture of what we are doing.

But I'm not going to try to force you to do things the way we do them.  I'm just saying this so you understand it's very difficult for me to give this the same amount of attention I usually give pull requests, because I'm limited by what I can see - maybe in the future try making an API with a usage and see if you like the result from doing it that way better.

**Comment by 4lejandrito** [comment]
Hi @Preston-Crary,

If you prefer we can work on the next story on top of this code and get it sent to you in a single pull request so you see the whole picture.

**Comment by 4lejandrito** [comment]
No problem, will do that. Thanks @Preston-Crary!

**Pull request closed without merging**
