### PR TITLE
LPS-97485 

### PR DESCRIPTION
**Pull request by martamedio**
Hey @Preston-Crary 

I reviewed the changes you sent me about this _ModelPermission_ issue and simply added a commit to delete the deprecated module at the package since we're performing a major change.
I have manually tested the [failing test in the previous PR](https://github.com/martamedio/liferay-portal/pull/174) and they all work locally, so that failures aren't related to our changes.

I'm going to launch the whole test suite again into this PR to make sure we're not missing anything else, but I think this is ready to send to BChan.

Thanks! 

cc/ @topolik

### CODE REVIEW

**Comment by martamedio** [comment]
ci:test

**Comment by topolik** [comment]
Thanks Marta

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
@vicnate5 can you check to see if there's any unique failures?

**Comment by vicnate5** [comment]
3 unique poshi failures on the default test suite
https://testray.liferay.com/home/-/testray/case_results/1242642495
https://testray.liferay.com/home/-/testray/case_results/1242644752
https://testray.liferay.com/home/-/testray/case_results/1242642494

Will re-run locally as that will be faster than a full retest. The "Relevant" suite has no unique failures.

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
ci:test:poshi

**Comment by vicnate5** [comment]
@Preston-Crary I was unable to run the failing tests locally because they do not pass on my machine, even with a normal upstream bundle. Re-running on CI.

**Comment by vicnate5** [comment]
ci:test:poshi

**Comment by vicnate5** [comment]
@Preston-Crary This is good. Sorry for the delay.

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/91714

**Pull request closed without merging**
