### PR TITLE
LPS-135504 Update Form test cases

### PR DESCRIPTION
**Pull request by koor4356**

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test:acceptance-functional

**Comment by koor4356** [comment]
ci:test:relevant

**Comment by koor4356** [comment]
ci:test:stable

**Comment by koor4356** [comment]
ci:test:acceptance-functional

**Comment by koor4356** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
@vicnate5 @koor4356 please go head and forward this if it looks safe, thanks!

**Comment by vicnate5** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/106853

**Pull request closed without merging**
