### PR TITLE
LPS-79309

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-79309

I completely refactored the fix from the last time you took a look.  I found I didn't actually need to do anything major with LanguageImpl, but rather was able to have the group/company locale bags return the correct results the first time.

Also, I couldn't get master HEAD to compile due to some npm issues, so I tested my changes on a commit about 4000 commits behind.  I can provide that branch, or try retesting on HEAD if you need.

Let me know if you have other questions.  Thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
Hi @ChrisKian,

this solution looks much better.  One potential problem I see is using LocaleUtil.getDefault(), since that uses a thread local.  I think a better change might be to use the companies default locale directly rather than the thread local value (normally that's what we're doing anyway).

I'm going on vacation next week so if you can't wait for it to be reviewed, the tests pass here and can use the company default locale without any test failures (some tests might are relying on the ThreadLocal) you can send it to him directly.  Otherwise I'll take a look when I get back.

Thanks!

**Comment by ChrisKian** [comment]
Hey Preston,
I don't believe the review is pressing, so I won't forward unless it becomes urgent.  I've pushed one additional commit regarding the use of COMPANY_DEFAULT_LOCALE over getting it from a thread locale.  I've updated the tests with the same change, and they all still pass.

Let me know if you have any questions, thanks!

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:stop

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by NorbertKocsis** [comment]
Hi Preston,

A customer needs the fix which causes this regression. Could you please prioritize the review?

Thanks,
Norbert

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by NorbertKocsis** [comment]
Hi Guys,

Any news on this one? Can I help in any way?

Br,
Norbert

**Comment by Preston-Crary** [comment]
Hi @NorbertKocsis,

this one is pretty involved and I've been pretty busy making sure everything we need fixed for the release is done in time.  Every time we fix something with Friendly URLs we break something else with them so I'm also considering this a risky change that needs some time to review.  If this is causing major problems for a customer please go ahead and provide them with a temporary patch.

**Comment by NorbertKocsis** [comment]
Hi,

Thanks for the update! Then I will create a patch for them.

**Comment by Preston-Crary** [comment]
@ChrisKian, sorry there's a merge conflict.  Can you rebase it?  I'll try to review it the day you resend it.

Thanks

**Comment by ChrisKian** [comment]
See https://github.com/Preston-Crary/liferay-portal/pull/554

**Pull request closed without merging**
