### PR TITLE
LPS-58106 master

### PR DESCRIPTION
**Pull request by juangon**
Hi @Preston-Crary. These are the changes that improves VerifyPermission performance in 6.2.x having huge numbers of Layout and permissions (5 minutes vs more than an hour).

In the end, solution approach was creating temp column in the same ResourcePermission table instead of creating a new table. This will save a JOIN between two huge tables that decreases performance.

Before doing that backport, in order to be consistent, I would like to forward the same code to master.

Please can you review as soon as possible?

Thanks very much!

/cc @achaparro

### CODE REVIEW

**Comment by Preston-Crary** [comment]
@juangon 
Sorry, I won't be able to look at this today.  I'll try to find time this week.

**Comment by juangon** [comment]
No problem @Preston-Crary. Thanks!

**Comment by Preston-Crary** [comment]
Did you test this with more than 1 million rows?  We've had faster ways to do this before that failed with 10 million rows :(

**Comment by juangon** [comment]
No, I didn't. I tested with the LPS script, the same that failed in QA using  the previous fix. I don't see any reason why this fix won't work for more DB records (a JOIN between 2 huge tables is worse than a JOIN with just 1 huge table I guess). In any case, you could increase the numbers in the script attached to the LPS when populating data to confirm it when reviewing.
Thanks!

**Comment by juangon** [comment]
CNQA confirmed the performance improvements with this fix:
6.2.x: From 1hr 40 minutes to 6 minutes (6.2.x has already the previous fix backported)
master: From 15 minutes to 6 minutes
So, seems all branches improves at least...

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/3059

**Pull request closed without merging**
