### PR TITLE
LPS-86435 Ignoring when the component is no longer active

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @Preston-Crary,

This pull is ready to go to master. 

I am concerned about [the last commit](https://github.com/Preston-Crary/liferay-portal/pull/765/commits/7b82942e1e37aad6e13ff0eabc7dec3689cc5c74) though. The permission logic consumer API was not designed to be dynamic. It keeps the references to the permission logic even when the sharing modules are stopped. That's the simplest way I found to make sure the code doesn't run in that case.

Thanks

**Comment by 4lejandrito** [comment]
@adolfopa

**Comment by Preston-Crary** [comment]
I'll take a look and do some testing today.  I'm pretty sure we can leave out 3558d09 and 7b82942 because the sharing configurator component should become inactive and cause the DL permission registrar to deactivate as well when the configuration changes.  But I'll do some extra testing to make sure this is the case.

**Comment by 4lejandrito** [comment]
I think the last one can be left out because DM stops working if `sharing-service` is stopped. 

Is there a way in which we can avoid this? It would be preferable to keep working even if sharing is stopped.

**Comment by 4lejandrito** [comment]
I did set a breakpoint in the registrar and it doesn't stop when modifying the configuration and that's why I made https://github.com/Preston-Crary/liferay-portal/commit/3558d09928d25f9c314a9018331c221d31304c02.

**Comment by Preston-Crary** [comment]
Is having DL work without sharing a requirement?  I can get it to work but it will be more code to maintain.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/7781

**Pull request closed without merging**
