### PR TITLE
LPS-140646 Remove BlogsStatsUser

### PR DESCRIPTION
**Pull request by ctang3**
Sorry about that, had the term order for getting the lastPostData and entryCount from the result row object switched  (and also had something cast to Integer instead of Long) :sweat_smile:

### CODE REVIEW

**Comment by Preston-Crary** [comment]
@ctang3 no worries. One of the big reasons of reducing duplication is it's easier to have good test coverage and catch these typo type problems. Just avoid pushing on a branch that's in review unless it's something specifically asked for or you can message saying you found a problem because otherwise the reviewer doesn't know what they're reviewing or if it's ready. Again no worries, I made the same mistake years ago :)

**Comment by Preston-Crary** [comment]
@slnn please check this against the blogs performance test case. If there's a problem please send us tracing and sampling profiles, thanks!

**Comment by slnn** [comment]
Hi @Preston-Crary 

Here are test results on Blog, from results a stable and small regression appeared.


Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry
-- | -- | -- | -- | --
BaseLine | f7a5f84 | 11976 | 289 | 373
BaseLine | f7a5f84 | 11970 | 259 | 351
PR | - | 11813 | 469 | 499
PR | - | 11848 | 491 | 499

Detailed test results zip and CPU tracings please see:https://drive.google.com/drive/folders/1knyZnfrCGKn1Lc0e3VXUNH4_C80tUCwB?usp=sharing

Regards
Lily

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/10384

**Pull request closed without merging**
