### PR TITLE
LPS-135504 conflicts 4

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
@vicnate5 when the other way and made forms use title case. Brought in the test commits you made earlier, I think some other ones are needed.

This is all the remaining conflicts. Can you check it after the tests are run, thanks!

**Comment by Preston-Crary** [comment]
ci:test:acceptance-functional

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by koor4356** [comment]
@vicnate5 I sent PR Preston. https://github.com/Preston-Crary/liferay-portal/pull/1488

**Pull request closed without merging**
