### PR TITLE
LPS-68104

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-68104

I tried to break up the commits in a way which made sense to me.  Let me know if I missed anything.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by lipusz** [comment]
Guys,

Looks like (based on the labels and the BPRs) that this LPS has already been released in a fix pack so no new commits should be pushed under this ticket. Can you double-check this?

**Comment by ChrisKian** [comment]
Hey @lipusz,

I believe the LPS was already released, but it was later reverted.  See https://github.com/brianchandotcom/liferay-portal-ee/pull/15014.  Do I need to create a new LPS for this issue and close the old one (LPS-68104)?

Thanks!

**Comment by lipusz** [comment]
Hi Chis,

I'd ask the ER team (Zoltán Takács) how they would like to handle this situation. I just got confused by the 2 portal fix pack number on the same LPS that is still in review.

**Comment by Preston-Crary** [comment]
@ChrisKian,

Here's some things we should change:
1. We need another integration test for the InlineSQLHelperImpl with tests for each scope (company, group, individual, group template), not involving any Finder.  Just make assertions on the SQL string that it returns.  Make sure to include queries with group by and order by.
2. Send two pull requests: one for the journal changes with the journal finder test and one with the InlineSQLHelper changes and it's test, that way we avoid the sub repository problem.  Send the portal one first so we can make sure that's in before the journal one.
3. From looking at the changes I think we need to keep the groupIdField parameter for group roles that a user has in one site but not in another site to prevent them from seeing content they are not supposed to see instead of removing it in 9d64ac5.  We should have a test for this by having two groups and two assets that require the same site role and a user that is only a member of one of the sites - we might already have a test for this, add one if we don't.
4. Let's go ahead and use a new ticket for this since it's already been backported and reverted in a backport to avoid confusion.

**Pull request closed without merging**
