### PR TITLE
LPS-76994

### PR DESCRIPTION
**Pull request by mbowerman**
Hi @Preston-Crary,

Unfortunately, I don't know why the lazy evaluation for layout resource permissions was added, since it was added so long ago and our only form of documentation is a vague commit message. The eager evaluation seems to have been added in https://github.com/liferay/liferay-portal/commit/7dd4d185a50003de88eb5d57ec4e3fe00e1bcb7b, which is also in 2006 and does not have any explanation as to why it was added. My guess is that the lazy evaluation was added as a failsafe in case if someone was using the portal before the eager evaluation was added. 

When I looked through the portal for any usages of `layoutPersistence#update` and `LayoutUtil#update`, the only results (aside from the previously discussed BaseImpl methods, which are not called by any Liferay code) were usages that could not be adding a new Layout to the database, aside from `LayoutLocalServiceImpl#addLayout`, which was also adding the resources. I also was unable to find any instances of Layouts being added via direct SQL. Since these are the only ways in which a Layout can be added to the database, it shouldn't be possible (aside from customizations) to add a Layout to the database without also adding the resource permissions for it.

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test

**Comment by mbowerman** [comment]
ci:stop

**Comment by mbowerman** [comment]
ci:test

**Comment by mbowerman** [comment]
I force-pushed my changes.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/5554

**Pull request closed without merging**
