### PR TITLE
LPS-100999 Make document library change tracked

### PR DESCRIPTION
**Pull request by stsquared99**
There's actually a bug with this one. When you upload a file to a changelist, there is an exception. I've included the log below to see if you can tell at a glance, otherwise I can dig deeper.

### CODE REVIEW

**Comment by stsquared99** [comment]
[LPS-100999.txt](https://github.com/Preston-Crary/liferay-portal/files/4037788/LPS-100999.txt)

**Comment by Preston-Crary** [comment]
Were you viewing in production when this happened?

**Comment by stsquared99** [comment]
No, with a changelist checked out, I upload a file in document library. Once it completes, that exception is thrown and the actual file is missing.

**Comment by Preston-Crary** [comment]
@stsquared99, when you resend this let's add in the CTDisplayRenderers and the ConstraintResolvers for DLFileEntry, DLFileVersion and DLFolder.

**Pull request closed without merging**
