### PR TITLE
LPS-77671 Remove from whitelist

### PR DESCRIPTION
**Pull request by pedroqueiroz94**
\\cc @rafaprax

### CODE REVIEW

**Comment by Preston-Crary** [comment]
@rafaprax There's a lot of forms functional test failures on https://github.com/pedroqueiroz94/liferay-portal/pull/69

@jpince can you take a look at those and provide steps to reproduce some of the failures?  This shouldn't change the UI at all.

**Comment by pedroqueiroz94** [comment]
@Preston-Crary , the functional test are failing for known issues. We have open tickets to fix those. Don't worry about them. :)

**Comment by Preston-Crary** [comment]
@pedroqueiroz94 But it says "Failures unique to this pull", how are those known failures?  Unless that message is wrong?

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
I'll run it again, to double check.

**Comment by jpince** [comment]
@vicnate5 can you please monitor this if any QA help is needed?

**Comment by pedroqueiroz94** [comment]
There are failing tests here there were not failing in our original pull request. We will investigate and send you another PR later. Thanks! :)

**Comment by pedroqueiroz94** [comment]
We fixed the NPE in this PR: https://github.com/brianchandotcom/liferay-portal/pull/55001. 

So I am reopening this and re running the tests.

cc. @rafaprax

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/5668

I left out 72a2e1d, since this change isn't going to be backported.  Those will be added back in once we cut the 7.1 branch.

**Pull request closed without merging**
