### PR TITLE
LPS-79262 Cache is not cleared after create, delete, create for the same object

### PR DESCRIPTION
**Pull request by moltam89**
Hi @Preston-Crary ,

this issue is about normalizing the **java.util.Date** and **java.sql.TimeStamp** objects, as their String representation is different, which causes problems when the finder cache is cleared.

Previously I created an [SME request](https://issues.liferay.com/browse/LPP-29886) for this problem, where you can find additional details.

Could you please review this pull request?

Thanks,
Tamás

### CODE REVIEW

**Comment by moltam89** [comment]
ci:test

**Comment by moltam89** [comment]
ci:retest

**Comment by moltam89** [comment]
I can't see the connection between this fix and the failing tests.

**Comment by Preston-Crary** [comment]
We decided to fix it in the ServiceBuilder.  Please see https://github.com/shuyangzhou/liferay-portal/pull/6115

**Pull request closed without merging**
