### PR TITLE
LPS-83181 Use Character.isSpaceChar to detect nbsp;

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @joshuacords

Notes from Josh:
> https://issues.liferay.com/browse/LPS-83181
> 
> The root of this problem is the body of the Message Board contained "&-nbsp;" as it's whitespace and the StringUtil.shorten() method does not see "&-nbsp;" as a place to break, so it just defaults to cutting the text at the character limit.
> 
> StringUtil used Character.isWhitespace() to find word ends when shortening text, however that method looks for what Java considers a space and will not find non-breaking spaces as is stated in it's [description](https://docs.oracle.com/javase/7/docs/api/java/lang/Character.html#isWhitespace(char)). The better method to use is Character.isSpaceChar() which finds whitespace characters based on Unicode standards which is more appropriate, description [here](https://docs.oracle.com/javase/7/docs/api/java/lang/Character.html#isSpaceChar(char)).

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
@joshuacords which usage of StringUtil.shorten is this being used in the ticket?

**Comment by joshuacords** [comment]
Hello @Preston-Crary, sorry I missed your comment. This is where StringUtil.shorten() is being used https://github.com/joshuacords/liferay-portal/blob/f353aaceb84e75f6f7196e40ab7f9c54231a6cca/portal-kernel/src/com/liferay/portal/kernel/search/Summary.java#L63

If you need anything else let me know.

**Comment by Preston-Crary** [comment]
Hi @joshuacords,

I don't think this is the right way to fix this.  I tested with replacing the no break spaces with dashes and was still able to see part of a highlighting element.  I think this needs to be handled in the Summary.getContent() method to make sure there are never any unlucky highlighting elements getting cut.

Can you make the needed changes there and send to the search team?

Thanks

**Comment by joshuacords** [comment]
Hi @Preston-Crary,

My mistake on the comment I made, I added the "-" to the nbsp so that it would actually be displayed. I am just talking about regular & nbsp ; which StringUtil.shorten() doesn't see as a space.

**Comment by Preston-Crary** [comment]
@joshuacords that's not my point at all.  I'm saying you may have fixed it for this one case but there's still a larger problem when not using that character.  Let me know when you have time to talk about this one so we can make sure we're on the same page.

**Comment by joshuacords** [comment]
Hi @Preston-Crary, I understand what you were saying now. I'll go ahead and add logic for this in  Summary.getContent().

**Comment by joshuacords** [comment]
Changes made and resent here: https://github.com/arboliveira/liferay-portal/pull/563

**Pull request closed without merging**
