### PR TITLE
LPS-132448 dslQueryCount()

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
@vicnate5 this is a service builder change. I think I got all the related failures resolved, can you double check and forward to Brian if it's safe.  Thanks!

**Comment by vicnate5** [comment]
ci:forward

**Comment by vicnate5** [comment]
No unique failures found.

Manually forwarded
https://github.com/brianchandotcom/liferay-portal/pull/102260

**Pull request closed without merging**
