### PR TITLE
LPS-86554

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@Preston-Crary can you review this pull I got from https://github.com/brianchandotcom/liferay-portal/pull/64440

It seems like AssetDisplayContributorFieldTrackerImpl is unnecessary OSGi component creation.. please review pull. Thx!

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Hi @Preston-Crary, we changed so that no component is used, you can check it out here. Thanks!

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
