### PR TITLE
Add custom variable names to Service Builder

### PR DESCRIPTION
**Pull request by arthurchan35**
Hi Preston,
We have an entity named as MFAFIDO2CredentialEntry,
right now the service builder will generate variable names **mfafido2CredentialEntry***,
while desired variable names would be **mfaFIDO2CredentialEntry***

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
Do we also need plural variable name?

**Comment by Preston-Crary** [comment]
CC @shuyangzhou

**Comment by arthurchan35** [comment]
> Do we also need plural variable name?

Based on my understanding, if we are going to support plural form of custom variable, then it has to be another custom attribute right? ie plural-variable-name in dtd file.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/9405

**Comment by Preston-Crary** [comment]
@arthurchan35 yes, that's correct.  I'm going to leave this one up to Shuyang.

**Pull request closed without merging**
