### PR TITLE
COMMERCE-7204 enable ct for commerce-product

### PR DESCRIPTION
**Pull request by ctang3**
https://issues.liferay.com/browse/COMMERCE-7204

Hope the commits aren't difficult to review. For some entities that are parents of others, I created the TRD for the other entities related to it in that commit. Let me know if you want it organized differently.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
We don't need 2ebce36 after all, can you drop that commit and build services

**Comment by Preston-Crary** [comment]
Please merge 22e18b353bb457d6aab30ffc1bd4a9ec97692bd1 with the commit creating that class.

**Comment by Preston-Crary** [comment]
Please merge 33036df9039518b552afc9485988ddb965fcd879 with the test creation commit.

**Comment by ctang3** [comment]
> Does e63617b make it so CTInstance test is passing? Should we drop that commit too?

Dropped this commit. Also remade the branch since I needed to cherrypick the tests from a bunch of other commits, so closing this PR. 

Please see https://github.com/Preston-Crary/liferay-portal/pull/1510, thanks!

**Pull request closed without merging**
