### PR TITLE
LPS-88060 [TS]

### PR DESCRIPTION
**Pull request by jcampoy**
https://issues.liferay.com/browse/LPS-88060 cc/ @pavel-savinov

### CODE REVIEW

**Comment by jcampoy** [comment]
ci:test

**Comment by Preston-Crary** [comment]
Sorry, reviews are going to be delayed for maybe a week or so.

**Comment by jcampoy** [comment]
ping @Preston-Crary

**Comment by Preston-Crary** [comment]
Hi @jcampoy,

I'll try to take a look at this later today or early tomorrow.

**Comment by Preston-Crary** [comment]
Please see my comment here:
https://issues.liferay.com/browse/LPS-88060?focusedCommentId=1707390&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1707390

**Comment by jcampoy** [comment]
Thanks @Preston-Crary , please review my answer because developers are using this other way:
https://issues.liferay.com/browse/LPS-88060?focusedCommentId=1708044&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1708044

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/7402

**Pull request closed without merging**
