### PR TITLE
[TECH SUPPORT] LPS-31549

### PR DESCRIPTION
**Pull request by giros**
Hi @Preston-Crary 

I'm sending this to you since you are marked as the support SME for performance. See https://issues.liferay.com/browse/LPS-31549 for details.

This is a performance tuning change for the database query of AssetEntryFinder. It improves the perfromance when we have to filter the asset entries by tags, e.g. when we configure Asset Publisher to do so.

The entire change is based on the pattern of https://issues.liferay.com/browse/LPS-28364 which did basically the same for categories.

Maybe AssetEntryFinder is not used anymore from AssetPublisher on our master branch, but it could still be used from any custom code, so this enhancement would prove useful.

Let me know if you have any questions.

Regards,
G

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
@giros

Can you include the times you had before and after the solution on the LPS for steps 4-7?

**Comment by giros** [comment]
Hey @Preston-Crary,

I actually didn't do a load test, because of 2 reasons:

- The concept and the pattern of the fix is pretty much the same as https://issues.liferay.com/browse/LPS-28364 did for categories. Therefore I only checked that the queries retrieve the same data as before this fix.
- A customer reported the actual performance issue from their production system's Asset Publisher that filters a lot of assets by tags, pointing out this very ticket. So it seems to be valid. They actually already got this fix as part of a support driven hotfix, and they are in the process of testing it. If you insist to get exact numbers for the improvement in order to forward this, I will wait for their feedback, as they are testing it against big amount of data.

Regards,
G

**Comment by Preston-Crary** [comment]
Okay, from the LPS it looked like we might have numbers already.  I've forwarded the pull request:
https://github.com/shuyangzhou/liferay-portal/pull/2032

**Pull request closed without merging**
