### PR TITLE
LPS-79309

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-79309

This should be the last PR.  I've fixed all the tests by ensuring the LocaleThreadLocal also has the relevant locale.  Let me know if you have any questions.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by ChrisKian** [comment]
Not sure why CI is failing, but it doesn't seem to be with my changes.  I've ran them all locally with no issues.

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
@ChrisKian I agree.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/6613

**Pull request closed without merging**
