### PR TITLE
LPS-104901 ModuleServiceLifecycle.DATABASE_INITIALIZED still needed

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
@stian-sigvartsen don't use the deprecated database initialized reference - I deprecated it because it's bad practice. Use the service your code needs, in this case you need to have a reference to CounterLocalService.  Fix everything from the reverted commit d67f790e96fd62ad934200d7bba55357769db459, not just the 2 upgrades but all 5.

Please resend with those 2 changes, thanks.

**Comment by stian-sigvartsen** [comment]
Thanks @Preston-Crary . Agree that is bad practice, but I guess the ModuleServiceLifecycle stuff was introduced in the first place because sometimes it is very difficult to use direct references. The proper fix is out of App Sec scope so I've assigned to Tina to see what can be done in the upgrade framework.

**Comment by Preston-Crary** [comment]
@stian-sigvartsen please review https://github.com/shuyangzhou/liferay-portal/pull/9410 so you can see what I meant by my previous comment.

**Pull request closed without merging**
