### PR TITLE
LPS-136385 Simplify details tabs and toolbar

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
Looks good

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
@suilin can you help with this functional failure? We renamed the "Unified" key to "Unified View", I'm not sure if there's another problem.

**Comment by suilin** [comment]
ci:test:publications

**Comment by suilin** [comment]
ci:test:bundle

**Comment by suilin** [comment]
Hi @Preston-Crary, I did a test-fix for the failure and sent to https://github.com/brianchandotcom/liferay-portal/pull/105047. No more issues were found related to this PR, details see [here](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1551153825).

**Comment by suilin** [comment]
ci:close

Sent to brianchandotcom#105047.

**Pull request closed without merging**
