### PR TITLE
LPS-79309

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-79309

See https://github.com/Preston-Crary/liferay-portal/pull/529

The changes also include the actual fix for LPS-79303, which is [this condition and statement](https://github.com/Preston-Crary/liferay-portal/commit/3499ac5e4034bee681bec5631c8d5e9dd8a95295#diff-00f6c7c30d950ae9c17b76ea1239377fR1026).

I also added tests to completely test the getDefaultLocale() method in every scenario which should be possible.  Further, by fixing [the one broken test](https://github.com/Preston-Crary/liferay-portal/commit/e713d13d6cb9d91ddfd8a82e8b3e642b7d11b8d9#diff-6deeaf2ed8481600be4419e8820b0070R189), I've also properly tested for the bug LPS-79309 references: a situation where we give an invalid locale and want to return the default locale since it's invalid.

Let me know if you have any questions.  Thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test

**Comment by ChrisKian** [comment]
All test failures look like this:

> junit.framework.AssertionFailedError: Active connection count differ before and after test for liferayDataSource expected:<1> but was:<2>

They seem unrelated to my changes.

**Comment by Preston-Crary** [comment]
Yep, we added that test rule to prevent leaked connections but I think it's not taking into account what other threads are doing.

It's might be a couple days before I can review this, things are getting crazy right now and this isn't needed to be in before release.

Can you double check your code and remove anything that is unneeded?  I found some dead code in your pull just by taking a quick look at it, I want you to look through it and make sure there aren't any unneeded lines.  I'm not telling you where the dead code is because whenever I do that people just fix the things I point out and leave other stuff I didn't point out and don't learn how to check their own code.

**Comment by ChrisKian** [comment]
Fair enough.  Would it be alright if I left my PR open and assigned to you in the process of removing dead code?  That way I can simply push my change(s) and run the CI again?

**Comment by Preston-Crary** [comment]
That's fine.

**Comment by ChrisKian** [comment]
Forwarded to https://github.com/Preston-Crary/liferay-portal/pull/536 since there was a large rebase and refactoring.

**Pull request closed without merging**
