### PR TITLE
LPS-104754 Auto SF

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by jesseyeh-liferay** [comment]
Regarding 60baa44, should `STATUS_DRAFT` be included? `7.2.x` only displays articles that are either `STATUS_APPROVED` or `STATUS_SCHEDULED`. I believe the commit message refers to my comment [here](https://issues.liferay.com/browse/LPS-104754?focusedCommentId=2025094&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2025094) which provides an example of how to set the statuses, but it should not be taken as an indicator of the actual statuses to set.

**Comment by Preston-Crary** [comment]
Hi @pavel-savinov @jesseyeh-liferay,

by changing the way the SQL is generated in CustomSQLImpl and the API of the QueryDefinition it is possible to have illegal queries if a unchanged finder impl is called with an array of statuses (params will be bound incorrectly).  So we have a big inconsistency because only part of the Impl is changed by this (CustomSQLImpl and JournalFolderFinderImpl).  Also try to avoid deprecating methods that still have usages, there are several hundred usages of the methods deprecated in this pull.

You have two options:
1. Update all the usages of QueryDefinition to use the array status method to bind all the status params so that they correctly handle multiple statuses.  This is difficult because there are many usages of getStatus(), isExcludeStatus() and setStatus().
2. Avoid changing QueryDefinition and CustomSQLImpl. You can fix this bug by only modifying journal code.

Either option is fine with us but we don't want to leave most of the portal having a not supporting a new QueryDefinition API causing lots of bugs and confusion later.

Let me know if you have any questions about this,
Thanks!

**Comment by adolfopa** [comment]
@Preston-Crary @pavel-savinov @jesseyeh-liferay We needed this fixed for GA1, so I've sent a revert to remove the usage of Item Selector in Journal Content.

After the release is done, we'll send a more conservative solution (ideally, local to Journal), reapplying Item Selector again.

Thanks!

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/83021

**Comment by Preston-Crary** [comment]
@adolfopa sounds good

**Pull request closed without merging**
