### PR TITLE
LPS-115011 Flip order

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
@vicnate5 can you check this test failure?

**Comment by vicnate5** [comment]
@Preston-Crary CI server was just really slow on that run, failure not related.

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/91215

**Pull request closed without merging**
