### PR TITLE
LPS-117723 Asset TableReferenceDefinitions

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
@vicnate5 @xbrianlee can one of you check this pull and let me know if there's any unique failures?

Thanks!

**Comment by xbrianlee** [comment]
@Preston-Crary I can take a look right now

**Comment by xbrianlee** [comment]
None of the issues are unique to this pull:
- PGDocumentsandmedia#DeleteDocumentInFolder failure caused by [LPS-117760](https://issues.liferay.com/browse/LPS-117760)
- The modules integration batch failed to start due to the error below. This seems to happen intermittently with Change List modules. Related to [LPS-114810](https://issues.liferay.com/browse/LPS-114810), but there are no consistent steps.
```
Service "com.liferay.portal.change.tracking.sql.CTSQLTransformer" is unavailable in 300000 milliseconds while setting field "_ctSQLTransformer" for class "com.liferay.portal.internal.change.tracking.hibernate.CTSQLInterceptor", will retry...
```

**Pull request closed without merging**
