### PR TITLE
LPS-136878 Add localization selector for translated titles and content

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
category
folder

We should make it consistent when something is translated but doesn't have content. Was expecting display to be grayed out for categories like it is for folders.

**Comment by stsquared99** [comment]
@Preston-Crary updated

**Comment by Preston-Crary** [comment]
Looks good, thanks!

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
ci:reevaluate:1277401_1024

**Comment by Preston-Crary** [comment]
@xbrianlee can you help with the functional test failure? Thanks!

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
@stsquared99 It looks like there's a bug when viewing the diff for conflicting changes.

Test Steps:
1. Add Web Content
2. Add Publication P1
3. Delete Web Content
4. Add Publication P2
5. Edit Web Content Title
6. Publish P1
7. Attempt to publish P2

Test Report: https://testray.liferay.com/reports/production/logs/2021-08/test-1-27/test-portal-acceptance-pullrequest(master)/1024/functional-tomcat90-mysql57-jdk8/5/19/LocalFile.Publications_ConflictingPublicationsNeedManualResolution/index.html.gz
after2

**Comment by stsquared99** [comment]
@Preston-Crary @xbrianlee I screwed up on the discard/conflict views. Let me fix that asap

**Comment by stsquared99** [comment]
@Preston-Crary @xbrianlee I fixed the bug as is.
If we want to add localization for the discard/conflict views, we can do that as a feature request.

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:close

Manually forwarded to https://github.com/brianchandotcom/liferay-portal/pull/106069

**Pull request closed without merging**
