### PR TITLE
LPS-71605 Keep ResourceBundleLoader a FunctionalInterface

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
hey @Preston-Crary, 
have you considered this pull? this does not bump any versioning, does it?

**Comment by csierra** [comment]
ci:retest

**Comment by rotty3000** [comment]
Hey @Preston-Crary this is the correct fix!

**Comment by Preston-Crary** [comment]
ci:stop

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/5403

**Comment by Preston-Crary** [comment]
Sorry @csierra, I just got really busy near the end of last week.  This looks fine.

**Comment by csierra** [comment]
sure... no worries.
we know you guys have a lot in your plate...
Thx again

**Pull request closed without merging**
