### PR TITLE
LPS-73606

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-73606
https://issues.liferay.com/browse/LPS-74001

Updated the PR based off your feedback [here](https://github.com/Preston-Crary/liferay-portal/pull/377#issuecomment-323482655).  Please let me know if there was anything I missed.  Thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
Test errors seem unrelated

**Comment by ChrisKian** [comment]
ci:reopen

**Comment by ChrisKian** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:stop

**Comment by Preston-Crary** [comment]
Yes, those are failing on every pull right now.  I should be able to take a look sometime tomorrow.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/4731

**Pull request closed without merging**
