### PR TITLE
LPS-129709 Add option to invite other users to collaborate on a publication

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
Hey @Preston-Crary, `PublicationsUpgrade#ViewOutOfDatePublicationsArchive7310` still [fails in this PR](https://testray.liferay.com/home/-/testray/case_results/1539354216) since we're unable to delete outdated publications from the kebab menu. Should this issue be fixed in this PR?(More context: [Slack thread](https://liferay.slack.com/archives/G01P4GXRC0Y/p1622731450045900?thread_ts=1622668882.044900&cid=G01P4GXRC0Y))

**Comment by Preston-Crary** [comment]
@xbrianlee fixed in f57d0fe. Thanks!

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by Preston-Crary** [comment]
ci:reevaluate:1257401_1161

**Comment by Preston-Crary** [comment]
ci:reevaluate:1257401_1161

**Comment by Preston-Crary** [comment]
ci:forward

**Pull request closed without merging**
