### PR TITLE
Lps 86234 86235 fix

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
Hi @arthurchan35,

how do we know which ones are effected?  There's nothing on the ticket telling me how we know these are the ones that need to be changed.

Shouldn't we add an upgrade for the old ones?

Please resend after adding the needed upgrade and explaining how to tell which ones should be changed.  We might be able to add a SF rule for this.

Thanks!

**Pull request closed without merging**
