### PR TITLE
LPS-89210 versioning fix for test

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by zoltancsaszi** [comment]
ci:test

**Comment by Preston-Crary** [comment]
There's a lot of functional test failures that are not failing on upstream.  Can you ask @vicnate5 or someone from QA if you're unsure how to test them and resend?

**Comment by vicnate5** [comment]
@kmaria most of the unique failures are with Staging tests

https://testray.liferay.com/home/-/testray/case_results/484461430
https://testray.liferay.com/home/-/testray/case_results/484461424
https://testray.liferay.com/home/-/testray/case_results/484461415
https://testray.liferay.com/home/-/testray/case_results/484377943
https://testray.liferay.com/home/-/testray/case_results/484460677
https://testray.liferay.com/home/-/testray/case_results/484438382
https://testray.liferay.com/home/-/testray/case_results/484430287
https://testray.liferay.com/home/-/testray/case_results/484463552
https://testray.liferay.com/home/-/testray/case_results/484463551
https://testray.liferay.com/home/-/testray/case_results/484460384
https://testray.liferay.com/home/-/testray/case_results/484460054
https://testray.liferay.com/home/-/testray/case_results/484460372
https://testray.liferay.com/home/-/testray/case_results/484463550

**Pull request closed without merging**
