### PR TITLE
LPS-75081

### PR DESCRIPTION
**Pull request by mbowerman**

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test

**Comment by mbowerman** [comment]
This is what I was talking about with some databases not supporting the escaped characters.

**Comment by Preston-Crary** [comment]
It doesn't need to match any database's syntax, we just need to remove the escape characters when we parse the function.

**Comment by mbowerman** [comment]
I don't understand why that would be necessary. If one database interprets "\" as an escape character, and a different database interprets it as a normal backslash character, shouldn't we only add extra parsing logic for the database that interprets it as the escape character? 

I also don't understand why you are saying we should remove the escape characters altogether. Can you give an example explaining why this would be necessary?

**Comment by Preston-Crary** [comment]
"I don't understand why that would be necessary. If one database interprets "\" as an escape character, and a different database interprets it as a normal backslash character, shouldn't we only add extra parsing logic for the database that interprets it as the escape character?"

Let's not focus too much on the performance part yet, right now the goal is to get the tests to pass and minimize how much extra database specific code we need to write for this.

"I also don't understand why you are saying we should remove the escape characters altogether. Can you give an example explaining why this would be necessary?"

The escaping is for our function, the processor needs to translate our function into something the database will understand.  After we've processed it do we still need the escape characters?  If we do then maybe we have to conditionally remove them for databases that don't know what to do with them.

**Comment by mbowerman** [comment]
> The escaping is for our function, the processor needs to translate our function into something the database will understand. After we've processed it do we still need the escape characters? If we do then maybe we have to conditionally remove them for databases that don't know what to do with them.

In that case, should I just remove SQLConcatTest#testConcatWithEscapedQuotes and resend the pull? Altering the SQL to replace the escape characters for databases that require something other than backslashes seems like it is outside the bounds of this LPS.

**Pull request closed without merging**
