### PR TITLE
LPS-110417 Unable to initalize My Account panel permissions after upgrade

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-110417](https://issues.liferay.com/browse/LPS-110417).<br><br>Hey @Preston-Crary, will you please look over my test case and solution for this issue? I'm not entirely sure that this is the best approach, but it's very effective for this case. I know it's possible that the fix should happen in the service layers for both PortletPreferences and ResourcePermissions, but since this issue only seems to appear with multiple threads, and I saw there was a similar solution used in https://issues.liferay.com/browse/LPS-104523, I decided to try synchronizing the method as a start. Let me know what you think. Thanks!<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:stop

**Comment by Preston-Crary** [comment]
Please see https://github.com/drewbrokke/liferay-portal/pull/1014

**Pull request closed without merging**
