### PR TITLE
LPS-78034

### PR DESCRIPTION
**Pull request by jonathanmccann**
@Preston-Crary,

Let me know if you have any concerns about these changes. For the actual LPS, only the first commit is necessary, but the other commits made sense after reading through the class.

Thanks.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/5738

**Comment by Preston-Crary** [comment]
@jonathanmccann FYI, you had to wrong ticket for your branch and commit messages. I updated them along with my changes.

**Comment by jonathanmccann** [comment]
Thanks for catching that and for your changes.

**Pull request closed without merging**
