### PR TITLE
LPS-116540 Reduce Changes View response size

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
Hi @stsquared99,

let finish normalizing the json structure.  It'll make it much easier to tune all the database fetching and reduce the size a bit more.  Can we structure it like this?

```
{
	"changes": [2, 3, 4],
	"contextView": {
		"1": {
			"2": {
			},
			"3": {
				"4": {
				}
			}
		}
	},
	"entries": {
		"1": {
			"classNameId": 1,
			"classPK": 10
		},
		"2": {
			"classNameId": 2,
			"classPK": 20,
			"editURL": "...",
			"ctEntryId": 101,
			"userId": 41
		},
		"3": {
			"classNameId": 2,
			"classPK": 30,
			"editURL": "...",
			"ctEntryId": 102,
			"userId": 41
		},
		"4": {
			"classNameId": 3,
			"classPK": 40,
			"ctEntryId": 103,
			"userId": 42,
		},
	},
	"renderCTEntryURL": "...",
	"renderDiffURL": "...",
	"rootDisplayClasses" {
		"type_name_1": [2, 3]
	}
	"spritemap", "...",
	"typeNames": {
		"1": "company"
	},
	"userInfo": {
		"41": {
			"name": "...",
			"portraitURL": "..."
		},
		"42": {
			"name": "...",
			"portraitURL": "..."
		}
	}
}
```

**Comment by Preston-Crary** [comment]
In this 1-4 is generated by the AtomicInteger.

**Comment by Preston-Crary** [comment]
If "contextView" needs to have all unique numbers we can add another field for the id used in "entries".

**Comment by Preston-Crary** [comment]
Looked at the structure more closely, it's pretty much the same as what I'm suggesting.  Only duplicate data left is the key and the names for the drop down items.  We can have the editURL name in a separate object "urlLabels": {"edit": "Edit"} and check if the entry has a editurl.

Main thing is the json building logic doesn't follow the new structure.  What we should do is flatten the tree in ViewChangesDisplayContext so we can process everything in batches of classNameId.  So instead of fetching the models in the _getChildren() method we should do fetch them all first after flattening the tree into a map of classNameId -> classPKs.

Let me know if I'm not being clear on something, thank!

**Comment by stsquared99** [comment]
@Preston-Crary No that makes a lot of sense, thanks

**Pull request closed without merging**
