### PR TITLE
[Technical-Support] LPS-67529

### PR DESCRIPTION
**Pull request by yuhai**
Hi Preston,

I hope your are well.

cc @daledotshan 

This PR extends from https://github.com/Preston-Crary/liferay-portal/pull/148

**Root issue:**
The issue is caused by part fix of LPS-28276.

When execute one delete command(including delete different models(bookmarks,dlfileentry, mbthreads) or some bookmark entrys, for example, auto-clean Recycle Bin: CheckEntryMessageListener execute:), if this delete failed and bookmarks delete logic has been executed, our resourceBlock table data won't be rolled back. This will affect bookmarks permission.

**Verfiy explanation:**
Only resourceBlock data is lost and its actually permission is existed in resourceblockpermission.
I assume there are 10 BookmarksFolder and they are using same resourceBlockId. The unclean data includes two kinds:
1. 10 datas are in Recycle Bin and they are all deleted( resourceBlock data is removed in resourceBlock table). This logic updateResourceBlock() will take care it.
2. 5 datas are in Recycle Bin and they are deleted  (resourceBlock data's referenceCount will be 5 in resourceBlock table, the normal value is 10). This logic (https://github.com/yuhai/liferay-portal/blob/4a0bddd647db9b90b02a20b0c562868dc1b5d2c9/modules/apps/collaboration/bookmarks/bookmarks-service/src/main/java/com/liferay/bookmarks/verify/BookmarksServiceVerifyProcess.java#L269-L274) will take care it.

For test, I don't have good way to express this. Because once ResourceBlockLocalServiceUtil execute, even though without fix, the commit will take effect.

Could you please firstly check the verify way is ok for you?

Regards,
Hai

### CODE REVIEW

**Comment by Preston-Crary** [comment]
This only fixes it for bookmarks, can you find a way to fix it in general that way Calendar and custom portlets are fixed as well?

**Comment by yuhai** [comment]
Hi Preston,

I add VerifyResourceBlock to do the general fix in portal-impl. For now, it should only apply for modules (calendar and bookmarks). The fix refers to JournalServiceVerifyProcess.verifyResourcedModels()->VerifyResourcePermissions.verify() way. Is this way ok?

Regards,
Hai

**Comment by yuhai** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
While testing these changes I found that there is an infinite loop that can occur in ResourceBlockLocalServiceImpl.updateResourceBlockId.  I'll look into it and post back here when I have an update.

**Comment by yuhai** [comment]
Thanks, Preston. :)

**Comment by dozeki** [comment]
Hello Preston, This is Daniel the Japan RSM. Thanks for working on this ticket. I just wanted to jump in here to see if there was any possibility in making this fix a priority. Our customer has been waiting for about 6 weeks now for this fix and I'm wanting them to not get angry. If there is anyway you can continue updating Hai on this fix and any way we can help to expedite please let us know. Also thanks Hai for the help. 

Thank you

**Comment by Preston-Crary** [comment]
Hi Daniel,
planning on making this a priority.  However, this is a difficult issue to solve.  I'll provide an update on this in the next couple days.

**Comment by Preston-Crary** [comment]
@yuhai @dozeki 
I've made some progress but am unsure about the correct solution.  @shuyangzhou should be in the office tomorrow and I'm hoping he can give some direction to the correct fix.  Since this is a client issue I've focused on the verify to correct their data (as long as the other bug is fixed in their environment they shouldn't see an issue after running the verify).

I'm currently testing the verify to confirm that it works on more databases than MySQL.  Once it does I'll provide a link to the verify so even if we don't have a full solution we'll have something to give to the client.

**Comment by yuhai** [comment]
Hi Preston, thanks for your help. :)

**Comment by Preston-Crary** [comment]
Please see https://github.com/Preston-Crary/liferay-portal/pull/154, the verify can be found on 6910744.  I wrote a test to replicate the issue on 4d64edc.  The verify is stable on the CI, so it's been tested on almost all of the databases we support, including Oracle.  Please go ahead and create a patch with the verify for the client after testing it yourself.

**Comment by yuhai** [comment]
Hi Preston,

Thanks for working on the ticket. I test verify code and find two issues:

1.  For the code https://github.com/Preston-Crary/liferay-portal/blob/69107443d8075af0449279bf9ad45ea583a43822/portal-impl/src/com/liferay/portal/verify/VerifyResourceBlocks.java#L47-L47, it will be false because com.liferay.bookmarks.model.BookmarksFolder register persistedModelLocalService after portal verify process finished. So the VerifyResourceBlocks verify process won't execute. 

2. Through checking _addMissingResourceBlocks() and _correctResourceBlockReferenceCounts() (I don't test this verify code due to 1) exist), it should miss one test case. Please refer to the test case:

Steps:
2.1. Create 2 bookmarkfolder (resourceBlockId =1, referenceCount:2).
2.2. delete the data(resourceBlockId =1) from ResourceBlock
2.3. Create 1 bookmarkfolder resourceBlockId =3, referenceCount:1). At here, if previous resourceBlockId =1 exist, it should use resourceBlockId=1 data, instead of create new resourceBlockId=3.
After applying verify code, it will add back resourceBlockId =1 data, expected behavior it should use 
resourceBlockId =3, and its referenceCount=3. Because three bookmarkfolder own same permission.

The function is expressed from https://github.com/yuhai/liferay-portal/blob/06d2164cc6c033ede734473470d3f7938b14f709/portal-impl/src/com/liferay/portal/verify/VerifyResourceBlock.java#L129-L135

For now, I think I can provide a verify code for the customer to clean their data on ee-6.2.x. For the root issue "resourceBlock table data won't be rolled back", we need to more time to fix it, is it right?

Regards,
Hai

**Comment by Preston-Crary** [comment]
@yuhai thanks for taking a look at it. Yes, let's go forward with the verify you had for 6.2.

**Comment by daledotshan** [comment]
Hey Preston,
Customer does not want to install the workaround fix they are going to wait for the final official fix.
How long do you think the final official fix take?

Also I have a question about the final official fix, remove the annotation about the transaction not a correct solution right? Did you get chance to discuss this issue with shuyang? 

Thanks,
Dale

**Comment by Preston-Crary** [comment]
I did get a chance to talk with him about it.  The time I have to work on this is going to be very limited.  The fix we decided would be best is to remove the ResourceBlock deletion from the local service and move it into the verify, this way we do not have the same race condition that ignores when the transaction is rolled back.

**Comment by Preston-Crary** [comment]
Please see https://github.com/yuhai/liferay-portal/pull/33

**Pull request closed without merging**
