### PR TITLE
[DO NOT MERGE] LPS-86435 Explicitly using the sharing permission logic from DL

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @Preston-Crary,

We have a bug where

**Comment by Preston-Crary** [comment]
Let's try to simplify this problem.  Here's how I think it could work well:
1. Sharing API has this interface:
```
public interface SharingModelResourcePermissionLogicFactory {
    public <T extends GroupedModel> ModelResourcePermissionLogic<T> create();// Use kernel permission logic interface.
}
```
2. Sharing service implements the interface, with the current logic being returned.
3. DL service module calls the SharingModelResourcePermissionLogicFactory in the permission registrar.

What do you think?  This seems like a reasonable and simple solution to this problem to me.

**Comment by 4lejandrito** [comment]
Hi @Preston-Crary,

So you susggest using a factory instead of exposing the permission logic itself, right? Sounds ok. I still need to test a few more edge cases so we will resend tomorrow. 

Thanks!

**Comment by Preston-Crary** [comment]
Two reasons:
1. I really don't like having marker interfaces especially when they extend other interfaces. I think this reduces possible semantic version changes as well (but that's not the main reason).
2. I don't want anyone to be tempted to add methods to the interface, factories don't usually change.
3. We can add parameter(s) to the create() method and have fields in the logic (maybe saving the classNameId in the logic itself).  I'm planning on looking into what we can save from the caller after you've resent the pull and updating it before forwarding.

**Pull request closed without merging**
