### PR TITLE
LPS-81706 Regenerate.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
I've seen a couple of places where the change was missing, and also that we were generating unused variables. Besides that everything looks good to me.

**Comment by Preston-Crary** [comment]
Hi @vicnate5,

are there any unique functional failures in this?

**Comment by vicnate5** [comment]
@Preston-Crary No failures related to this pull

**Comment by Preston-Crary** [comment]
@vicnate5 Thanks!

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/7146

**Pull request closed without merging**
