### PR TITLE
LPS-88060 [TS]

### PR DESCRIPTION
**Pull request by jcampoy**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
@jcampoy, is there some class you got the logic for bafd350 getPreferences() from?

**Comment by jcampoy** [comment]
Hi Preston,

Not really but  ModifiableSettings of the settings obtained via portletInstanceLocator delegates in PortletPreferences, see :

com.liferay.portal.service.impl.**PortletPreferencesLocalServiceImpl**.getPortletInstanceSettings 

and:

com.liferay.portal.kernel.settings.PortletPreferencesSettings.**PortletPreferencesSettings**(javax.portlet.PortletPreferences, com.liferay.portal.kernel.settings.Settings)

**Comment by Preston-Crary** [comment]
Okay, I'll try to take a look this afternoon.

**Comment by Preston-Crary** [comment]
Sorry, it's going to be a day or two before I can take a look, several other issues have come up.  I'll be sure to make time this week.

**Comment by jcampoy** [comment]
No problem, thank you for the update.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/7470

**Pull request closed without merging**
