### PR TITLE
[TS] LPS-92784

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-92784

Made changes based off [your comment](https://github.com/Preston-Crary/liferay-portal/pull/723#issuecomment-476910758).  I agree this is much better since the arguments of updateOrganizations method maps one user to many orgs, and setOrganization does exactly that.

Original comment:

> When attempting to add a new user to an org which already has existing users, the time it takes to add the new user scales up depending on how many users already belong to said org. Time goes up approximately 1 second per 20000 users.
> 
> The root cause is how long the Users_Orgs table mapping takes to iterate over all matches from the given SELECT statement. Currently, we are selecting all userIds which belong to the given organizationID, then determining if any match the newly added user (they never will because the user is brand-new). As the number of users belonging to the org increases, so does the time it takes to retrieve all userIds.
> 
> Since we are not able to blindly add an entry to the Users_Orgs table, the solution will be to essentially reverse the query. Instead of retrieving userIds belonging to the organizationId, we will retrieve organizationIds which belong to the new user's userId (this will always return 0, and is thus very fast and still achieves the same result we want).
> 
> Let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:stop

**Comment by Preston-Crary** [comment]
You can still use this fast way for your use case (like you did before) but not in general in this method, you still need to do the work that's in unsetOrganizationUsers(). There's some subscription task callback and removing user group roles that you're leaving undone.

**Comment by ChrisKian** [comment]
Resent here: https://github.com/Preston-Crary/liferay-portal/pull/726

**Pull request closed without merging**
