### PR TITLE
LPS-87037 use provide capability when other module langagues needed so that there's no need to override every specific module sharing a key.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
Hi @marianoalvarosaiz,

can you let me know how you knew to change these bundles? That way I can double check and make sure we didn't miss any.

**Comment by marianoalvarosaiz** [comment]
Hi @Preston-Crary,
 I only checked for the ones using _com.liferay.lang.merger_ plugin in the _build.gradle_ file (in master, not master-private, I will create a different LPS afterwards).

I discarded the UAD modules since they're just copying the key/value pair and substituying the key for a key only valid for that module, so in it's not a copy, it's just a way to speed and simplify the generation.

I also discarded it for _frontend-theme-fjord_ because I was not sure if it was appropriate since there's not a bnd.bnd file.

**Comment by marianoalvarosaiz** [comment]
In most of the cases what the plugin does is to copy the Language\*properties files inside a -lang module into the using module. So that, if for example there's a module-web that uses the plugin it will copy the module-lang (it it does exist) Language*properties file inside module-web. This implies, besides duplicating files, that if we need to override a key in the language module that is used in, for example, another 5 modules, we need to create 5 overriding modules, instead of just overriding module-lang keys.

> Is there some reason we need should remove com.liferay.lang.merger?

 So what we did is just add the module-lang module as a capability, so that the LanguageExtension adds it to the module-web ResourceBundleLoader, and if someone needs to override a lang module key they could do it by overriding only the lang module ResourceBundleLoader, and if they need to override a module-web specific key they can also do it overriding the web module ResourceBundleLoader

> Should we also remove or deprecate this plugin?

 I was thinking about it, but since it's used with parameters in the UAD modules and also in the  _frontend-theme-fjord_ module I don't now if we can get rid of it. Maybe we could add a SF rule to discourage its use in a common module.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/7066

**Pull request closed without merging**
