### PR TITLE
LPS-121096

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:change-list:norebase

**Comment by Preston-Crary** [comment]
ci:test:change-list

**Comment by Preston-Crary** [comment]
Hi @slnn, can we do a fixed 2000 session run against this pull for change tracking?

**Comment by slnn** [comment]
OK, got it

**Comment by slnn** [comment]
Hi @Preston-Crary 

It seems that on the current head of master, the data generated by SampleSQLBuilder need to be updated, I will fix it and run test with this pull later, I will update the test result when I got it.

Regards
Lily

**Comment by Preston-Crary** [comment]
ci:test:change-list

**Comment by slnn** [comment]
Hi @Preston-Crary 

Test results for this pull with 2000 fixed session count please see the google doc:
https://docs.google.com/spreadsheets/d/1_LaEuRWxYLMFFuE-9M_KaPlsek-u9Qp2MDadiznOQR8/edit?usp=sharing

Compared with Test 6 (Before LPS-121096), this pull (Test 7 (On LPS-121096)) improves the performance, especially on the DB CPU usage.


Regards
Lily

**Pull request closed without merging**
