### PR TITLE
LPS-69599

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @Preston-Crary,

Attached is an update for https://issues.liferay.com/browse/LPS-69599. I just wanted to get an extra pair of eyes on these changes since you had made some changes to these files previously.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by Preston-Crary** [comment]
Only thing I don't know is if the browser sniffer is supposed to be exclusive about which browser it is (only one method returns true with specific browsers).  The new test is the only one that asserts false on all the other browsers while all of the old tests only assert true on the one that's being tested.

I'm not sure which is correct, should we make sure that the others assert false or make this less picky?  Or is there some reason for it to be like this?

**Comment by jonmak08** [comment]
adding @blzaugg...thoughts?

**Comment by blzaugg** [comment]
Edge is a big fat liar, so I needed to add extra checks so it couldn't pretend to me other browsers.

I think the other methods could be improved, to be more exclusive, but I was only focusing on Edge.

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/51206

**Pull request closed without merging**
