### PR TITLE
95208d

### PR DESCRIPTION
**Pull request by SpencerWoo**
Moved method as mentioned in https://github.com/Preston-Crary/liferay-portal/pull/778#issuecomment-499576596

https://issues.liferay.com/browse/LPS-95208

> Test for impersonated user is not necessary to be included here because LPS-86545 (liferay@44dbaef) already handles testing for that use-case.

### CODE REVIEW

**Comment by SpencerWoo** [comment]
ci:test:backend-hypersonic

**Comment by SpencerWoo** [comment]
hi @Preston-Crary any update on this one?  thanks

**Comment by Preston-Crary** [comment]
Hi @SpencerWoo,

there's been several other higher priority issues come up in the last week or so.  I also had to take a little time off after getting sick (got back today).  Hopefully, if nothing too important comes up or things don't take longer than I think they should I can take a look at this tomorrow.

If you want to get this in quickly best thing to do is make sure the test covers the code that was added. Otherwise, I'll test it and if it's not covering the change and I'm unable to spend time fixing it then I'll have to reject the pull (which wastes both our time). Then you're have to change it and be back in the queue hoping no one cuts in front of you.

I realize that's not the nicest way of saying this, but I'm more interested in being clear and honest.

**Comment by SpencerWoo** [comment]
Sounds good!  we're good to wait so no problem, just making sure it wasn't forgotten.  The clarity is appreciated -- thanks again

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/7920

**Pull request closed without merging**
