### PR TITLE
LPS-136729 enable ct for repository

### PR DESCRIPTION
**Pull request by ctang3**
https://issues.liferay.com/browse/LPS-136729

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
@xbrianlee I think this one is good, can you double check and forward it if it's good, thanks!

**Comment by ctang3** [comment]
ci:forward

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
Continued in https://github.com/xbrianlee/liferay-portal/pull/663

**Pull request closed without merging**
