### PR TITLE
LPS-73874

### PR DESCRIPTION
**Pull request by holatuwol**
https://github.com/shuyangzhou/liferay-portal/pull/5766 without Servlet 3.1 upgrade

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by holatuwol** [comment]
ci:test

**Comment by Preston-Crary** [comment]
@holatuwol problem is in upstream... I'll retest once it's resolved.

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
The jsp compile failure has been fixed.

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by holatuwol** [comment]
ci:test

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/5826

**Pull request closed without merging**
