### PR TITLE
LPS-129709 Invite users for publications

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
@stsquared99 please rebase and send to @xbrianlee so he can update the functional tests. We removed the publish drop down control from the top menu so we need to do this part in 2 steps now, review changes and then publish.

**Comment by xbrianlee** [comment]
ci:test:bundle

**Pull request closed without merging**
