### PR TITLE
LPS-113032 Fix new random byte failures.

### PR DESCRIPTION
**Pull request by Preston-Crary**
CC @shuyangzhou

@hhuijser can we SF this?  Making files from random bytes can lead to files that cause TIKA errors during indexing.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
This is never going to end until we kill RandomTestUtil, that's the source of all evils.

**Comment by hhuijser** [comment]
@Preston-Crary does this (still) apply to master? (ticket says 7.2.x, 7.1.x)

`FileImpl._parseToString` no longer calls `org.apache.tika.Tika.parseToString` in latest master (logic was changed in the last couple weeks: https://github.com/liferay/liferay-portal/commits/master/portal-impl/src/com/liferay/portal/util/FileImpl.java)

**Comment by hhuijser** [comment]
nvm, I see it does happen in master still

**Pull request closed without merging**
