### PR TITLE
LPS-120856 Rename "Change Lists" to "Publications"

### PR DESCRIPTION
**Pull request by Preston-Crary**
@xbrianlee please send a follow up pull to rename the change-list test group and anything else QA related.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by xbrianlee** [comment]
`semantic-versioning-jdk8` failure is unrelated to the changes in this PR. 

@Preston-Crary If this PR fails again, feel free to manually forward this and link this comment.

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/94722

**Pull request closed without merging**
