### PR TITLE
LPS-89210 sample sql builder

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test:staging

**Comment by zoltancsaszi** [comment]
ci:test

**Comment by zoltancsaszi** [comment]
ci:test

**Comment by yichenroy** [comment]
ci:test
There was a ci-related failure, restarting test.

**Comment by Preston-Crary** [comment]
LayoutSetPrototypePropagationTest is failing as well as a bunch of Export Import tests, can you check them locally and resend after fixing the failures?

Thanks

**Pull request closed without merging**
