### PR TITLE
LPS-124347 Service bundle symbolic name validation fails to execute with invalid symbolic name

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
@vicnate5 please check this pull, there shouldn't be anything that can break as long as startup is working.

**Comment by vicnate5** [comment]
@Preston-Crary Looks good, no unique failures.

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/96603

**Pull request closed without merging**
