### PR TITLE
LPS-65965

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by daledotshan** [comment]
Current logical:
Check group admin right, if it is true, return the search result directly, if it is false, will check the do permission filter for the search result. So it the user has group admin right, will see all the search result even it is belong to other site(the use has no view right about it).

Changes:
Move group admin check into filter method, if the use has group admin for the document group will return true, otherwise, will do the document permission check.

**Comment by daledotshan** [comment]
Hey Preston,
I have some thing need to double check with you since you write this part of code.
1. Seems the isGroupAdmin method does not consider lucene document could cross site 

2.  the new way seems not good because it will check permission for every document, probably will cause performance issue. 

3. if no a good way about this issue can we just remove the optimization code about the group admin?

**Comment by daledotshan** [comment]
Hey Preston,
Do you have chance to look at this issue? it is for a ee customer.
Thanks,
Dale

**Comment by Preston-Crary** [comment]
@sherlyliu @daledotshan,

This is the wrong way to fix this.  The problem is that we expect the groupIds to be null if we are not specifying a group to search in.

So if we are searching "everywhere" searchContext.groupIds() should return null.  We get the false positive for being a group admin because we have documents in groups that are not included in the groupIds.

If the above is not possible, another way to fix it would be to have a way to see if we are checking "everywhere" from the search context and return false in the isGroupAdmin method.

Please email me if you want clarification or get stuck.

**Pull request closed without merging**
