### PR TITLE
[DS] LPS-98383 reading-time-service

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:backend-hypersonic

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci-test-relevant passed in https://github.com/dantewang/liferay-portal/pull/1210#issuecomment-513053579

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/8029

**Pull request closed without merging**
