### PR TITLE
LPS-136442 Refactor version comparison to compare with latest production version

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by stsquared99** [comment]
@Preston-Crary @xbrianlee
Screen Shot 2021-08-13 at 7 18 31 PM

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by xbrianlee** [comment]
ci:test:bundle

Looks like the functional test still breaks. I'll fix the test and forward this PR on Monday.

**Comment by xbrianlee** [comment]
ci:close

Continued in https://github.com/xbrianlee/liferay-portal/pull/615

**Pull request closed without merging**
