### PR TITLE
LPS-98197 solving outdated dlFolder for test DLFolderUADAnonymizerTest.testAutoAnonymizeStatusByUserOnly                                              DLFolderUADAnonymizerTest.testAutoAnonymizeUserOnly

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
// @4lejandrito

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
ci:test:backend-hypersonic

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/8099

**Pull request closed without merging**
