### PR TITLE
[TECHNICAL-SUPPORT] LPS-99574

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
@ryannealeigh please check your ticket number in your commit messages. I fixed it but it can be really confusing when looking at commit history if everyone misses it.

Please see https://github.com/shuyangzhou/liferay-portal/pull/8119

**Comment by ryannealeigh** [comment]
@Preston-Crary, thanks for catching that. I will make sure to double check next time.

**Pull request closed without merging**
