### PR TITLE
LPS-135504

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:acceptance-functional:norebase

**Comment by Preston-Crary** [comment]
@vicnate5 can you check the results for this one too, thanks again!

**Comment by vicnate5** [comment]
@Preston-Crary unique failures here, but looks like you actually fixed a broken lang key (the test seems to be expecting the broken one).

Will resend this to you after I confirm.

**Comment by vicnate5** [comment]
resent https://github.com/Preston-Crary/liferay-portal/pull/1458

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
