### PR TITLE
LPS-121067 Fail to Publish Web Content with Image field with a Publication

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by stsquared99** [comment]
@Preston-Crary Also my impl bnd.bnd updates when I deploy, but seems like that is a local issue since it shouldn't be due to my change.

**Comment by Preston-Crary** [comment]
Let's set the thread local In PortletFileRepositoryImpl instead of TempFileEntryUtil and JournalArticleImpl.

For the listeners I think we should use `CTCollectionThreadLocal.isProductionMode()` instead of the file suffix thing.

**Comment by stsquared99** [comment]
@Preston-Crary Do we want to still keep the count logic? Should the production check be the only check?

**Comment by Preston-Crary** [comment]
Yes.

**Comment by Preston-Crary** [comment]
Well actually, to be safe let's do the count but only if not production.

**Comment by stsquared99** [comment]
Resent: https://github.com/Preston-Crary/liferay-portal/pull/1221

**Pull request closed without merging**
