### PR TITLE
LPS-66047

### PR DESCRIPTION
**Pull request by mbowerman**
Hey Preston,

I tested this by starting up a fresh database with this fix included, and then starting up a separate fresh database without any of the commits from LPS-66047, and comparing the ResourceActions table of each database. Both tables had the same number of resourceActions (2482). For whatever reason, the resource actions seemed to get added in a different order in each database, but a cursory inspection made it appear that they had the same set of resource actions. And of course, I also verified that the problematic ADD_TAG action did indeed get added.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
That ThemeLocalServiceImpl warning has to be related to our changes, it's not on other pulls and it's very consistent on this one.

**Comment by mbowerman** [comment]
I noticed a bunch of tests are also failing because com_liferay_test_portlet_TestPortlet is not getting its Resource Actions set properly...

**Comment by mbowerman** [comment]
ci:retest

**Comment by mbowerman** [comment]
ci:retest

**Comment by mbowerman** [comment]
I removed the commits that cleared the ResourceActionsBag, hopefully that allows it to pass the tests.

**Comment by holatuwol** [comment]
ci:retest

**Comment by mbowerman** [comment]
ci:retest

**Comment by mbowerman** [comment]
ci:retest

**Comment by mbowerman** [comment]
ci:retest

**Pull request closed without merging**
