### PR TITLE
LPS-78661 Start language extension with corresponding resource bundle loader tracker to avoid race condition

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
@pavel-savinov, can you explain what the race condition is?
1. Which threads are racing?
2. What methods are involved?
3. How does this change resolve the race?

From looking at this change it's hard to know these things quickly and I want to know if some of our other extensions need a similar change.

**Comment by pavel-savinov** [comment]
@Preston-Crary in some **site-navigation-** modules we have TemplateHandler implementation.
In TemplateHandlerRegistryImpl there is a LifecycleListener which uses available TemplateHandlers to register the templates. We also have site-navigation-lang module which provides language keys for all those modules and in each module we do Provide-Capability to register an aggregate resource bundle using LanguageExtender.

And there are cases when TemplateHandler is starting when there is no aggregate resource bundle loader yet, and TemplateHandlerRegistryImpl fails to resolve corresponding language keys.
It doesn't happen if we start LanguageExtension when corresponding bundle is in Resolved state.

Steps to reproduce:
1) Start the Portal
2) Remove site-navigation-lang module from the osgi/modules folder
3) Add a breakpoint in TemplateHandlerRegistryImpl#292
4) Deploy site-navigation-lang(or just copy it back to osgi/modules)
5) Assert that keys in nameMap variable are not translated(sometimes they are, but it is easy to catch).

**Comment by Preston-Crary** [comment]
Hi @pavel-savinov,

thanks for the explanation.  This change does improve the problem but I think there's still some edge cases that are not fixed depending on which order the bundles are deployed / undeployed + other race conditions.

I'm going to work on a solution that will cover those edge cases as well.  It may take a couple days depending on if other issues take priority... I'll do my best to have a solution by the end of the week and link it here in case you want to take a look.

**Comment by pavel-savinov** [comment]
Thanks @Preston-Crary!

**Comment by Preston-Crary** [comment]
Ended up going with your solution in the end.  Please see my changes and comment on https://github.com/shuyangzhou/liferay-portal/pull/7921

Thanks!

**Pull request closed without merging**
