### PR TITLE
LPS-136442 CTDisplayRenderer refactoring

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
@xbrianlee can you check the functional test failure? I get a 404 when I click on any of the links.

**Comment by xbrianlee** [comment]
ci:test:bundle

@Preston-Crary [Here's](https://testray.liferay.com/reports/production/logs/2021-08/test-1-26/test-portal-acceptance-pullrequest(master)/226/functional-tomcat90-mysql57-jdk8/2/23/LocalFile.Publications_ConflictingPublicationsNeedManualResolution/index.html.gz) the test report for it. The diff view doesn't seem to be working properly. I'll build this branch to look into this further.
before3

**Comment by stsquared99** [comment]
@xbrianlee I was able to reproduce this myself, taking a quick look at it

**Comment by stsquared99** [comment]
@xbrianlee @Preston-Crary I see, this is kind of an edge case. The change is a modification. but the conflict is that it was deleted in production, so I am trying to compare against something deleted. I'll follow up with preston. It's a weird UX case to iron out

**Comment by stsquared99** [comment]
ci:close

**Comment by stsquared99** [comment]
Resent: https://github.com/Preston-Crary/liferay-portal/pull/1456
FYI @xbrianlee

**Pull request closed without merging**
