### PR TITLE
LPS-106397 | master

### PR DESCRIPTION
**Pull request by vicnate5**
@Preston-Crary resolves test compile issues from the DSL change. I made sure we closed the QA process gap that led to this being caught late. https://issues.liferay.com/browse/LPS-111632

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:backend

**Comment by Preston-Crary** [comment]
This looks fine, you can push it to Brian if this fixes all the test compile failures.

**Comment by vicnate5** [comment]
ci:forward

**Comment by vicnate5** [comment]
PMD Fix here https://github.com/brianchandotcom/liferay-portal/commit/dcaa59d522941ce3446c837d8d16ddf5485d82aa

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/87403

**Pull request closed without merging**
