### PR TITLE
LPS-110414 part 2

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
@vicnate5 still some random failures.

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:stop

**Comment by vicnate5** [comment]
@Preston-Crary Can you resend this and CC me? I can check the results and we then can push in right after in case it fails for random reasons again.

**Comment by Preston-Crary** [comment]
@vicnate5 decided to go in a different direction for now.  I'll come back to it later after making some progress on other parts.

**Pull request closed without merging**
