### PR TITLE
LPS-81028 Regenerate.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/6215

**Comment by Preston-Crary** [comment]
Hi @marianoalvarosaiz,

I reworded bace27d to have the correct ticket and forwarded it.

@shuyangzhou and I talked about this fix and decided to let the nulls miss the cache to try to make this change as safe as possible.  We can always come back after release and make a plan to cache the null values.

It's unsafe to cache them as different SQL is generated if the value is null instead of blank.  If we make the change you are suggesting people will be unable to query specifically for nulls.  We're not sure what the best thing to do is so were compromising performance a little bit to make sure the change is safe.

Normally 068d55a is excluded when regenerating.

Thanks!

**Comment by marianoalvarosaiz** [comment]
Thanks for your answer @Preston-Crary,
 regarding 

> It's unsafe to cache them as different SQL is generated if the value is null instead of blank. If we make the change you are suggesting people will be unable to query specifically for nulls.

The problem, I think, is not when querying specifically for nulls, since for the database query I use the unmodified parameter, but when first querying for null and then for empty. If for example you have a database with:
                articleId
recNo1     NULL
recNo2     ""

If you first query for an articleId = NULL you will get the recNo1 and when querying after for "" you will get the cached result without retrieving recNo2.
Anyway from the database model point of view this doesn't make sense:

1. We are saving two objects differently in the database that in Java are going to be the same (because of the getter transformation)

2. Depending on the database the behaviour would be different, since Oracle for example doesn't distinguish NULL from empty string, but MySQL does.

So if you are concerned about this point I think that the modification of the model setter to always convert (for convertNull strings) null to empty, and always search in database (in these cases) for _is NULL or is EMPTY_ should be considered.

Related to 
> @shuyangzhou and I talked about this fix and decided to let the nulls miss the cache to try to make this change as safe as possible. We can always come back after release and make a plan to cache the null values.

I find that the solution simply stores in the cache and doesn't use the item because of the checks it does after between the getter and the parameter, so we always query the database. If that was the intention maybe it should be better to not use the cache in those cases and at least we save memory.

One last point is that the solution is probably not backporteable to 7.0.X, because we cannot remove a property in the middle of a version.

Kind regards.

P.D: Because I'll be on holidays a couple of days I'm adding Cristina, Jose and Alberto to see if the can follow the issue.
/cc @crodriguezy, @jcampoy, @almonwork

**Comment by Preston-Crary** [comment]
@marianoalvarosaiz our current procedure is all changes to the service builder are backported to 7.0.x - there's is only one service builder for both 7.0.x and 7.1.x.  All changes we make have to account for this.  While I agree this isn't the best solution, the business value of working on this is low so we're going to spend our time on more important things as we're very close to the release.

I hope you can accept that we agree this should be worked on at some point but now is not the time to work on it.

**Comment by Preston-Crary** [comment]
Hi @marianoalvarosaiz,

can you resend this solution but make sure to solve the case for arrayable parameters?  Leave out 31c8779 and 068d55a and try to make the diff is as small as possible.  Can you assign back the parameter value instead of creating a new *NullSafe String?

Thanks

**Comment by marianoalvarosaiz** [comment]
Hi @Preston-Crary,
 thanks, I will prepare the PR.
Kind regards.

**Pull request closed without merging**
