### PR TITLE
LPS-88424

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@Preston-Crary see https://github.com/brianchandotcom/liferay-portal/pull/66424

**Comment by joshuacords** [comment]
Minor change and forwarded here: https://github.com/Preston-Crary/liferay-portal/pull/642

**Comment by joshuacords** [comment]
ci:close

**Comment by Preston-Crary** [comment]
@joshuacords can you resend with the changes we talked about?

Thanks!

**Pull request closed without merging**
