### PR TITLE
LPS-98200 | master

### PR DESCRIPTION
**Pull request by jpince**
https://issues.liferay.com/browse/LPS-98200

@preston-crary, can you please help with the  failures? See results in https://github.com/petershin/liferay-portal/pull/581#issuecomment-511058759. They all fail with this error , though mariadb adds . Hopefully that's helpful.

This is not a critical priority, but can you look into it within the next two weeks?

### CODE REVIEW

**Comment by jpince** [comment]
Links to modules-int console logs:
mariadb: https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/310419/AXIS_VARIABLE=7,label_exp=!master/consoleText
mysql: https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/303930/AXIS_VARIABLE=7,label_exp=!master/consoleText

This needs to go to Peter Shin when you're done. Thanks!

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test

**Comment by Preston-Crary** [comment]
Looks like the ModulesStructureTest failure is about having the build marker in the deprecated module.

The other issue is that the deprecation test is running against those module and deleting their tables.  I'm still not totally clear, do we want these to be deprecated still or not?

If not we should update DeprecatedModulesUpgrade and remove the parts for those modules.

**Pull request closed without merging**
