### PR TITLE
LPS-66776 Using progressive bi-linear scaling

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @Preston-Crary 

Following your suggestion in https://github.com/Preston-Crary/liferay-portal/pull/191#issuecomment-251160131 I applied the progressive bi-linear scaling algorithm that thumbnailator uses by default, in our own code.

It produces the same good quality images as the library does, but without relying on it.

Best regards,
István

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:reopen ci:retest

**Comment by Preston-Crary** [comment]
@IstvanD what's the performance difference compared to how we were doing it before?

**Comment by IstvanD** [comment]
@Preston-Crary 

The performance results for setting the kangaroo image as profile and running both the single and progressive scaling 1000 times

```
Simple Scale: 63 ms
Progressive BL Scale: 21382 ms
Simple Scale: 80 ms
Progressive BL Scale: 21445 ms
Simple Scale: 50 ms
Progressive BL Scale: 21451 ms
Simple Scale: 46 ms
Progressive BL Scale: 21517 ms
Simple Scale: 57 ms
Progressive BL Scale: 23464 ms
```

They are roughly the same as  by running the same test for thumbnailator.

**Comment by Preston-Crary** [comment]
@IstvanD thanks, just wanted to confirm we didn't cause a performance regression when we implemented the strategy ourselves.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/3262

**Comment by IstvanD** [comment]
Sure. Thanks for forwarding!

**Pull request closed without merging**
