### PR TITLE
delete{entityName} methods modified to throw the inherited exceptions whether is it versioned or not

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
Hi @Preston-Crary ,

We need these changes to successfully use the serviceBuilder in our commerce + changeset prototype.

Please, consider them.

Thanks,
Zoltan

**Comment by zoltancsaszi** [comment]
And my other question is, how we supposed to use the versioning API? 
Do we have to write our own CRUD methods in the LocalServiceImpl or is it automatod?

**Comment by Preston-Crary** [comment]
@zoltancsaszi the service is a published into OSGi as a VersionService with a model.class.name property.  Using the service to publish, create drafts, check out a previous version and such is left to the developer using the ServiceBuilder to do since I don't know you're business rules.

If you need to have multiple tables be versioned together you can use a VersionServiceListener and register it with the VersionService, I would recommend this over overriding the methods.

**Comment by Preston-Crary** [comment]
How does a253ada conflict with WorkflowedModel?  If you have a WorkflowedModel then the method will be generated with the WorkflowedModel.isDraft() implementation, if you're using the latest ServiceBuilder and portal-kernel then it shouldn't be a problem.

**Comment by Preston-Crary** [comment]
Please see:
https://github.com/shuyangzhou/liferay-portal/pull/6690
https://github.com/shuyangzhou/liferay-portal/pull/6691

**Comment by zoltancsaszi** [comment]
@Preston-Crary thanks for the answers. I will check it. 
Actually we won't need the publish-draft system, we only want to use the Version table part of the framework per now.

**Comment by Preston-Crary** [comment]
@zoltancsaszi one thing to keep in mind is the Version table is considered immutable.  You should not try to update a version if you are using the table directly. I recommend at least using the publish method to maintain versions even if you don't need the other methods.

**Comment by zoltancsaszi** [comment]
Thanks. 
Actually, we redesigned our concept so we won't use this kind of versioning for now.

**Pull request closed without merging**
