### PR TITLE
LPS-93457 No need to escape '=' due to FELIX-4743. Add double backslash due to FELIX-5609 (configuration is typed).

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
This looks good to me @marianoalvarosaiz, I think CI is fairly stable now. Just want to confirm everything is passing before forwarding it.

**Comment by vicnate5** [comment]
@Preston-Crary @marianoalvarosaiz No unique functional test failures on this PR.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/7622

**Pull request closed without merging**
