### PR TITLE
LPS-138143 Add preview in content display for documents

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by stsquared99** [comment]
@Preston-Crary 
This is really just to see all the pieces that we are working with. It's a real mess, but technically doable?

**Comment by Preston-Crary** [comment]
Does this work with showing diffs?

**Comment by Preston-Crary** [comment]
I'm sure it doesn't do highlighting but I'm wondering if it totally breaks.

**Comment by stsquared99** [comment]
@Preston-Crary It does not work with diffs. Part of the resource url for the previews actually contains the version number, so that alone creates a difference in the html

**Comment by Preston-Crary** [comment]
So should we have something in the API that decides if we want to allow highlighting?

**Comment by stsquared99** [comment]
@Preston-Crary Personally, I feel like that would be the simplest and also clearest way to do it. Diffable is false by default, for content

**Comment by Preston-Crary** [comment]
Okay, let's go with this way for now. Let's go ahead and clean up the impl:
- I think the different processors can just use field references instead of methods
- Some collections like `documentMimeTypes` duplicate the ones from their processors, we should use the methods on them to get the mime types
- Pretty sure we do not really want to throw an exception in all those cases, I think returning null should work

**Comment by Preston-Crary** [comment]
Please see https://github.com/stsquared99/liferay-portal/pull/177

**Pull request closed without merging**
