### PR TITLE
LPS-101086 Apply view count service to MBThread

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by stsquared99** [comment]
CI test results passed here: https://github.com/stsquared99/liferay-portal/pull/91

**Comment by Preston-Crary** [comment]
https://github.com/Preston-Crary/liferay-portal/blob/a590321ba5837c74b6322b4194ed4a7ba42d0574/modules/apps/calevent/calevent-importer/src/main/java/com/liferay/calevent/importer/internal/verify/CalEventImporterVerifyProcess.java#L870

**Comment by stsquared99** [comment]
@Preston-Crary I remember why I create the entry instead of just using increment. The increment method takes an int, while the value is a long.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/8579

**Pull request closed without merging**
