### PR TITLE
LPS-95203 Ensure there's service.bundleLocation property in fileinstall configurations.

### PR DESCRIPTION
**Pull request by achaparro**
Hi @Preston-Crary,

For now we have added the fix in the OSGI configuration as a verify in ConfigurationPersistenceManager. However I think we should handle this as an upgrade process since we just need to run the changes once, not anytime we startup the module. For that reason we have created the following ticket:
https://issues.liferay.com/browse/LPS-95352

@marianoalvarosaiz will take care of it.

Thanks!

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
@achaparro we would have used an upgrade process if it was possible. For this table it's completely separated from all other APIs. We need access to the Release table to run an upgrade but the release service is not ready until after we have configurations (chicken-egg problem), we may be able to refactor that dependency at a later time or add a table to manage upgrades in the future.

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/7755

**Pull request closed without merging**
