### PR TITLE
LPS-89648

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-89648

Sent directly to you from https://github.com/Preston-Crary/liferay-portal/pull/663 as per your comment here https://github.com/Preston-Crary/liferay-portal/pull/663#issuecomment-459060770

Let me know if you have any questions.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
@ChrisKian, can you please test your change and resend once you fixed the issue?

**Comment by Preston-Crary** [comment]
I'm pretty sure you didn't test it since your null check is backwards.  Using it if it is null instead of not using it and || instead of &&.

**Comment by ChrisKian** [comment]
Sorry about that, it's been a day

**Pull request closed without merging**
