### PR TITLE
LPS-67079

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @Preston-Crary 

I keep getting semantic versioning issues with this one.
You have an idea what's going on?

**Comment by hhuijser** [comment]
@Preston-Crary 

Now it has merging conflicts as well.
Can you see what happens when you take this pull and redo the updating cache?

**Comment by Preston-Crary** [comment]
Yes, I'll take a look sometime this week.

**Comment by hhuijser** [comment]
Thanks @Preston-Crary !

**Comment by hhuijser** [comment]
We got it in: https://github.com/brianchandotcom/liferay-portal/pull/42155

**Pull request closed without merging**
