### PR TITLE
LPS-89294

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
@knchau can you explain how this helps?  It's just hiding the stacktrace, I'm not really sure what this fixes. It's possible through configuration to mute the GroupServiceHttp through log4j configuration, why can't they just do something like that if they want to avoid the stacktrace?

**Comment by knchau** [comment]
@Preston-Crary, the purpose of this ticket was to handle the ConnectionException log thrown. The user can still see that a network error occurred, but would not be overwhelmed by the stacktrace. 

I'm not certain if we should mute the GroupServiceHttp, but it can still be an option. However, @zsoltbalogh requested it to be done like this: https://github.com/moltam89/liferay-portal/pull/482#issuecomment-475201951, https://github.com/zsoltbalogh/liferay-portal/commit/c2b1f868b7cbca13070e6eabe51b3c8de5ca0930.

**Comment by Preston-Crary** [comment]
@knchau okay, let's [inline the method](https://refactoring.guru/inline-method) and do special exception handling logic there.

This way we don't have to update the template and we can quite the connection exception for this one case.

Thanks!

**Comment by knchau** [comment]
@Preston-Crary, there seems to be complication when attempting to inline the method. The GroupServiceHttp methods call *ServiceUtil classes using class(). Inline the method with no changes will work as expected, but fails the sf check:

`Task :apps:export-import:export-import-service:formatSource`
`Use @Reference instead of calling GroupServiceUtil directly, see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/osgi_components.markdown: ./src/main/java/com/liferay/exportimport/internal/staging/StagingImpl.java (SourceCheck:JavaOSGiReferenceCheck)`

Error occurs here: https://github.com/knchau/liferay-portal/commit/d4413b9ac7b49e0399efd556c8d7e639a2d72327#diff-17058a1a92394a536877d9abdf7779efR1919

I followed the documentation, but the reference created returns a different object, throwing an error in the process. Is there another approach to avoid failing the sf check?

**Comment by Preston-Crary** [comment]
@knchau you should be able to create a method handler by doing this:

```
MethodHandler methodHandler =
	IdentifiableOSGiServiceInvokerUtil.createMethodHandler(
		targetObject, method, arguments);
```

The targetObject would be a reference to GroupLocalService. 

Hold the method as a field like in https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/util/impl/JournalContentImpl.java#L481-L492

You shouldn't inline the method everywhere, only where you need to. I thought you only needed to inline the one usage in StagingImpl, are the other ones really needed?

**Comment by knchau** [comment]
@Preston-Crary, I tried your suggestions above and it didn't work for me. It threw the same error (end of file exception). I also tried referencing GroupService as the targetObject since GroupLocalService does not contain the method getGroupDisplayURL.

I'll attach my committed changes if you'd like to check if I did things correctly: b2e1fddcb74f57ceac335673a8fd9c963abccfa3

Do you have any other suggestions?

As for inlining the method, I did inline the method in other cases because they would occur when navigating throughout the Staging tab (i.e. publish to live) - but I have changed it to only inline the one usage in StagingImpl.

**Pull request closed without merging**
