### PR TITLE
LPS-105974 Data Partitioning: CompanyInfo table 

### PR DESCRIPTION
**Pull request by achaparro**
Hey @Preston-Crary,

I have created the companyInfo table as we agreed. Mike, Brian and I had decided to separate just the key column for now since it's the only one which contains sensitive information.

Anyway, we store the companyInfo at attribute in the companyImpl so we will be able to add more columns in the future easily.

Cheers!

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Ci:test:relevant

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/8663

**Pull request closed without merging**
