### PR TITLE
LPS-117402

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
Hi @arthurchan35,

can you copy the pattern from com.liferay.layout.admin.web.internal.upgrade.v_1_0_3.UpgradeLayoutTemplateId.  There's no reason to have concurrent auto batch for this, just call runSQL() and move it to the calendar web module.

Please send this to @achaparro, thanks!

**Pull request closed without merging**
