### PR TITLE
LPS-100930 Using onBefore for cases when the file has already been removed

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @Preston-Crary,

Our model listener was being passed `null` in our `onAfterRemove` method. We've fixed by changing it to `onBeforeRemove` but I feel there might be something wrong on the calling infrastructure. 

Can you please have a look?

Thanks!

**Comment by 4lejandrito** [comment]
@adolfopa

**Comment by 4lejandrito** [comment]
@jkappler

**Comment by Preston-Crary** [comment]
@4lejandrito null is a valid value.  It means the object was never saved to the database.   I think for your code you can just add a null check and return.

**Pull request closed without merging**
