### PR TITLE
COMMERCE-7203 Apply mvcc to products

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
@ctang3 sorry thought I CC'd you in the last comment.

**Comment by ctang3** [comment]
No worries 😀 Fixed the test and resent here: https://github.com/Preston-Crary/liferay-portal/pull/1526

**Pull request closed without merging**
