### PR TITLE
LPS-66047

### PR DESCRIPTION
**Pull request by mbowerman**
Hi Preston,

Brian Chan was saying that he wouldn't merge the fix because it was failing too many tests, so I rebased it onto the latest version of master and reran the CI a couple of times ([see results here](https://github.com/mbowerman/liferay-portal/pull/12)). For all the failures, I was either able to find several examples of current pull requests that they were also failing (all the RSS-related stuff, testPMDJava, testGenerateAndInsertSampleSQL, testSourceFormatter), or else they failed inconsistently and appeared to have nothing to do with my changes (FileImplExtractTest.testJpg, BBCodeTranslatorUtilTest.testEmoticonDescriptions).

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:retest

**Comment by mbowerman** [comment]
ci:retest

**Comment by mbowerman** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by mbowerman** [comment]
These all appear to be failing on other pulls.

https://github.com/brianchandotcom/liferay-portal/pull/42328
https://github.com/brianchandotcom/liferay-portal/pull/42326

**Comment by Preston-Crary** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/42330

**Pull request closed without merging**
