### PR TITLE
LPS-129709 Add option to invite other users to collaborate on a publication

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by stsquared99** [comment]
@Preston-Crary How does this look? It seems like I should just check for ct enabled companies, don't need further logic than that. Also some of the code duplication from role local service seems unavoidable
Thanks!

**Comment by Preston-Crary** [comment]
@stsquared99 looks good :)

ci:forward

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/103620

**Pull request closed without merging**
