### PR TITLE
LPS-114473 Trash CT

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
@xbrianlee, is this unique to this pull?  I know there was some big UI changes for control panel recently.

**Comment by xbrianlee** [comment]
ci:forward

@Preston-Crary This looks to be a fluke. The menu item wasn't ready by the time the test interacted with it. Retriggering the run.

**Comment by Preston-Crary** [comment]
@xbrianlee can you provide manual steps I can use to test this?  It seems like a real problem.

**Comment by xbrianlee** [comment]
ci:forward

Sorry I realized that this was a test failure caused by the recent addition of the Global Menu. https://github.com/liferay/liferay-portal/commit/d8f7b4b13a1111b5940b4411651510edd4386754 should resolve that test failure.

**Comment by Preston-Crary** [comment]
@xbrianlee thanks!

**Pull request closed without merging**
