### PR TITLE
LPS-110414 part 2

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
@vicnate5 looks like we have some random failures still.  Already trying to send a fix for the versioning failures here https://github.com/Preston-Crary/liferay-portal/pull/1014

**Comment by vicnate5** [comment]
@Preston-Crary Quarantining the the `Depot*` tests, the other 2 functional failures should not happen on re-run.

https://github.com/brianchandotcom/liferay-portal/pull/87292

**Comment by vicnate5** [comment]
We also just added Semver test to Brian's origin, to prevent the versioning issues in the future.

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
Reviewed by QA. Integration test failures on this PR are unrelated.

**Comment by vicnate5** [comment]
@Preston-Crary Just real issues left here.

**Comment by Preston-Crary** [comment]
ci:forward

**Pull request closed without merging**
