### PR TITLE
LPS-89170

### PR DESCRIPTION
**Pull request by danielkocsis**
Hi @Preston-Crary,

I did the changes you suggested. Although, the upgrade part is a bit tricky. Even though `SELECT ... INTO ...` is an ANSI SQL statement, but MySQL for example doesn't support it at all, so I had to drop it. I compared all the ANSI compliant solution and it seems the best option is to run a standard `CREATE TABLE` and then run an `INSERT INTO SELECT`. But, there is one more issue, how to generate the prim keys for the new Version entities? I also tried a few options to here, but as row numbering is vendor specific again (Oracle), and other solutions like the `AUTO INCREMENT` constraint, sequences, etc... are also varies by vendors I decided to reuse the PK of the original LayoutSet entity, which is unique by nature for sure. 

There are 2 issues I have right now:
 1. The source formatter doesn't know the `INSERT INTO SELECT` statement, so it applies a weird formatting to it...
 2. The sequence generates the PK for the Version should be put to the very last PK value + 1, that we created during the update

 + 1 CI was absolutely unreliable today, but I run a full upgrade from 6.2 to master locally and it seemed fine, however CI would be really useful anyway ...

Could you please help with these issues?

cc'ing: @matethurzo  

thanks,
Daniel

### CODE REVIEW

**Comment by danielkocsis** [comment]
ci:test:relevant

**Comment by danielkocsis** [comment]
ci:test:sf

**Comment by danielkocsis** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
1. Formatting looks good enough to me, if SF isn't complaining that's fine.
2. The LayoutSet primary key sounds like what I would have done :)
3. Just need to add some Counter insert statement to the upgrade.
4. Please merge the two autogenerate commits, so it's clear what part is generated from adding versionend=true and your other changes, the 2nd commit is undoing some of what the 1st regen commit is doing.

For Counter just use two inserts with a MAX select on the LayoutSet primary key and hardcode the two names, one for LayoutSet and one for LayoutSetVersion.

Thanks, almost there!

**Pull request closed without merging**
