### PR TITLE
LPS-87933 InlineSQLHelperImpl doesn't honor Site Admin for multiple groupIds

### PR DESCRIPTION
**Pull request by topolik**
Hi Preston,

Fixed the transactional call from https://github.com/Preston-Crary/liferay-portal/pull/622. Let's see how tests run this time.

Thanks.
https://issues.liferay.com/browse/LPS-87933

### CODE REVIEW

**Comment by topolik** [comment]
ci:test

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
@vicnate5, can you help me with the test results?  Is this one safe?  It looks safe to me but it has unique failures.

**Comment by vicnate5** [comment]
@Preston-Crary No functional failures unique to this pull

**Comment by topolik** [comment]
Hi guys, I'm afraid some test failures are real. I can reproduce some failures locally, don't know the reason yet. Will keep you updated. Thanks.

**Comment by vicnate5** [comment]
@topolik which failure are you reproducing?

**Comment by topolik** [comment]
`com.liferay.dynamic.data.mapping.service.test.DDMStructureServiceTest` failures. Without my changes it passes. It's the `TransactionalTestRule` that breaks the test methods, I'm investigating what's the problem there.

**Comment by topolik** [comment]
Please see https://github.com/Preston-Crary/liferay-portal/pull/633. Thanks.

**Pull request closed without merging**
