### PR TITLE
Lps 135504 bnd

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:acceptance-functional

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
@vicnate5 does the functional test results look okay? I sent a pull fixing the unit test compile failure and running relevant again since some of the tests got aborted.

**Comment by vicnate5** [comment]
@Preston-Crary One real failure here.

Missing lang key here:
langKey


Steps to Reproduce:
1. Add a new Web Content article
1. Go to Edit the default home page of DXP
1.  Add Fragments > Heading to the page
1. Click the Heading fragment to bring up sidebar on the right
1. Choose Heading > element-text
1. Go to Mapping tab > Item > Select Item
1. Select the created Web Content
1. Click "Field" selector
1. `display-page-url` missing lang key

**Comment by Preston-Crary** [comment]
ci:test:acceptance-functional

**Comment by Preston-Crary** [comment]
@vicnate5 fixed by f00351d.

**Comment by vicnate5** [comment]
@koor4356 can you check the new results here?  (check for poshi failures from lang key issues)

**Comment by koor4356** [comment]
Looks good. No unique poshi failures from lang key issues.

**Comment by Preston-Crary** [comment]
Thanks guys, please see https://github.com/brianchandotcom/liferay-portal/pull/107236

**Pull request closed without merging**
