### PR TITLE
LPS-119008 Don't allow Staging to be enabled when Change Lists is enabled and vice versa

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:foward

**Comment by Preston-Crary** [comment]
ci:foward

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by xbrianlee** [comment]
The `SitetemplatesUsecase#SiteTemplatePageLinkInWebContentRedirectCorrectly` failure above is  flaky based on its [failure history](https://testray.liferay.com/home/-/testray/cases/867538096/view?p_p_state=normal&orderByCol=createDate_sortable&orderByType=desc&statuses=3). It looks like we're not reliably selecting the right iframe before making that assertion.

Other than that the test results look good to me 👍

**Comment by Preston-Crary** [comment]
@xbrianlee thanks!

Please see https://github.com/brianchandotcom/liferay-portal/pull/93391

**Pull request closed without merging**
