### PR TITLE
LPS-90402

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-90402

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
@holatuwol, can you remove the constructors for both the key and value maps?  The other usages are broken in the same way.

**Comment by holatuwol** [comment]
ci:stop

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/7358

**Pull request closed without merging**
