### PR TITLE
Lps 75529

### PR DESCRIPTION
**Pull request by lanceji92674957**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
@lanceji92674957 I thought you were going to update all the usages of ZipReader, is there any reason you didn't remove all the calls to ZipReader.close() to use try-with-resources?

**Comment by lanceji92674957** [comment]
I was going to do it on a separated ticket. Should I combine these two things together?

**Comment by Preston-Crary** [comment]
Yes do them together, without any usages it's unclear why we're adding the API.

**Comment by lanceji92674957** [comment]
ok, I'll send you the replacement with try-with-resources for in 7.0.x-private, subrepo first,
then ZipReader, and replacement for expected exceptions in test after that

**Pull request closed without merging**
