### PR TITLE
LPS-135504

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:acceptance-functional:norebase

**Comment by vicnate5** [comment]
ci:test:acceptance-functional:norebase

**Comment by vicnate5** [comment]
@koor4356 Please scan results. Should have no more unique failures after the latest fix.

**Comment by koor4356** [comment]
@vicnate5 there is a conflict with this branch. The ci is still running. Therefore, I was not able to do an analysis in the morning. Thank you!

**Comment by vicnate5** [comment]
ci:test:acceptance-functional:norebase

**Comment by koor4356** [comment]
@Preston-Crary  @vicnate5, This PR looks good except the branch has a conflict. No unique failures. Thank you!

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/106386

**Pull request closed without merging**
