### PR TITLE
LPS-105579 Upgrade with PostgreSQL: column "ctcollectionid" of relation "layout" already exists

### PR DESCRIPTION
**Pull request by achaparro**
Hi @Preston-Crary,

During the tests for DataPartitioning I have discovered this. This should fix it.

Cheers!

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/81831

**Comment by Preston-Crary** [comment]
Thanks @achaparro !

**Pull request closed without merging**
