### PR TITLE
LPS-71605 Keep ResourceBundleLoader a FunctionalInterface

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
@csierra this is still going to fail versioning.  For any of the failing tests click on the link, then click console output.  You can see if you look through the output which failure was first, the one reported on the pull is often just a symptom of the real problem, especially when there are many test failures.

**Comment by csierra** [comment]
hey @Preston-Crary, 
why do you say this is going to fail versioning? could you explain to me what is the change that forces the version change?

**Comment by Preston-Crary** [comment]
@csierra, look at the failures from the last pull:
https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/174185/AXIS_VARIABLE=2,label_exp=!master/consoleText

Search for "VERSION INCREASE REQUIRED".

It's complaining about the methods you removed, even though you have a default method to replace them.  I'm not sure if this is a bug with the versioning tool or if after compiling with the old code and running with the new code would cause an AbstractMethodError.  If a AbstractMethodError is thrown then it is not a bug with the version tool but an actual major version change.

You can see the symantic version failure by running "ant clean deploy" in portal-kernel with your changes.

**Comment by csierra** [comment]
hey @Preston-Crary, 
> It's complaining about the methods you removed, even though you have a default method to replace them. I'm not sure if this is a bug with the versioning tool or if after compiling with the old code and running with the new code would cause an AbstractMethodError. If a AbstractMethodError is thrown then it is not a bug with the version tool but an actual major version change.

thanks for the explanation. We are going to open a discussion for this to figure out what is the correct outcome. 

So then I guess we can simply add the `default` method and keep the impl as they are for the moment. 

Thanks.

**Pull request closed without merging**
