### PR TITLE
[TECHNICAL SUPPORT] LPS-84809

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-84809

Hi @Preston-Crary 

This is bug is caused by [LPS-71868](https://issues.liferay.com/browse/LPS-71868), you implemented it in following pr: https://github.com/shuyangzhou/liferay-portal/pull/4100

In order to fix it, I am adding **getLayoutChildLayouts** to methods handled by wrapReturnValue.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by jorgediaz-lr** [comment]
ci:reopen

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:stop

**Pull request closed without merging**
