### PR TITLE
LPS-75081

### PR DESCRIPTION
**Pull request by mbowerman**

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test

**Comment by mbowerman** [comment]
ci:stop

**Comment by mbowerman** [comment]
ci:test

**Comment by Preston-Crary** [comment]
The expected test annotation argument doesn't enforce the reason the exception happened.  Can you update the tests with `Test(expected = IllegalArguementException.class)` to instead do this:

```
try {
    // Cause exception

    Assert.fail();
}
catch (IllegalArguementException iae) {
    Assert.assertEquals("expected exception message", iae.getMessage());
}
```

You can just add another commit at the end and push this branch.

**Comment by mbowerman** [comment]
I pushed two new commits.

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
@mbowerman Thanks!

I'll try to take a look at this sometime this week but things are really crazy this month so it might sit here until next week.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/5767

**Pull request closed without merging**
