### PR TITLE
LPS-66950 use latest available portal impl dependency

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
@Preston-Crary Here goes second part of LPS-66950. Thanks!

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by pavel-savinov** [comment]
@Preston-Crary Could you please check SF on this pull? The thing is that I do SF locally and it works with no errors...

**Comment by Preston-Crary** [comment]
From looking at the error message it seems like the SF error is in UpgradePermission.

**Comment by pavel-savinov** [comment]
@Preston-Crary Yes, but how can I detect it and fix it when my local SF passes without errors? Can you run SF on your machine to check if it is only my problem or something in CI server?

**Comment by Preston-Crary** [comment]
Sure, I'll try to review this tomorrow sometime.

**Comment by Preston-Crary** [comment]
Hi Pavel,

can you resend after updating e62755f.  Please remove the getBitwiseValues and checkActions methods and embed that logic into the query (make multiple queries if necessary), it's possible to do bitwise checks on the database side using MOD(?, ?) as long as the query goes through the SQLTransformer.  There are some examples in RoleFinder and portal.xml.

Thanks!

**Pull request closed without merging**
