### PR TITLE
LPS-96700 unique endpoint graphql

### PR DESCRIPTION
**Pull request by nhpatt**
This overrides https://github.com/Preston-Crary/liferay-portal/pull/783 (that has a bug). Sorry for the trouble.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
@nhpatt is that the reason we're leaving out https://github.com/Preston-Crary/liferay-portal/pull/783/commits/9b2b4fe59a7703ea155dcda9a0be0bbb2c2542ed ?

**Comment by nhpatt** [comment]
No, didn't saw the sf commit, will update

**Comment by nhpatt** [comment]
-- updated

**Comment by Preston-Crary** [comment]
Cleared my other tasks today, I should have time to review this tomorrow.

**Comment by nhpatt** [comment]
No hurry :)

**Comment by Preston-Crary** [comment]
Please see https://github.com/nhpatt/liferay-portal/pull/142

**Pull request closed without merging**
