### PR TITLE
LPS-101083 Apply view count service to DLFileEntry

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by stsquared99** [comment]
ci:test

**Comment by stsquared99** [comment]
@vicnate5 These look like the only potential unique ones, they look random or unrelated
https://testray.liferay.com/home/-/testray/case_results/878477390
https://testray.liferay.com/home/-/testray/case_results/878481694
https://testray.liferay.com/home/-/testray/case_results/878501864
https://testray.liferay.com/home/-/testray/case_results/878483091
https://testray.liferay.com/home/-/testray/case_results/878481337
https://testray.liferay.com/home/-/testray/case_results/878501878

**Comment by vicnate5** [comment]
@stsquared99 Not related.

**Comment by stsquared99** [comment]
@Preston-Crary This one should be good to go

**Comment by Preston-Crary** [comment]
Please resend, need to fix or remove DLFolderFinderImpl.FIND_FE_BY_G_F_FETI and RepositoryModelReadCountComparator.

**Pull request closed without merging**
