### PR TITLE
LPS-120877 Discussion support for publications

### PR DESCRIPTION
**Pull request by Preston-Crary**
CTMessageLocalServiceImpl#getMessages returns a list of Message.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by xbrianlee** [comment]
Manually forwarded in https://github.com/brianchandotcom/liferay-portal/pull/100983

**Comment by xbrianlee** [comment]
ci:close

**Pull request closed without merging**
