### PR TITLE
LPS-78226

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-78226

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
@holatuwol I think this last failure is caused by your changes.  We changed what version of the module is being published but not which version is being consumed, so users of those packages now don't have the version they need.  To make this change we would need to update all the modules to have project dependencies in their build.gradles.

**Pull request closed without merging**
