### PR TITLE
[DS] LPS-99123 mobile-device-rules-service

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:backend-hypersonic

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/8113

**Comment by Preston-Crary** [comment]
Hi @ChiZelin,

please be careful with stuff like f82d8610ac17fa87020bcc89b491e6cdd8d992b6.  Pretty sure that did not compile.  You cannot use `@Reference` on static fields, you have to create a static setter method otherwise DS will reject it, but that is not good practice.

For these static utils to resolve circular dependencies for local services.  We want them to not have any fields or service util usages.  To do them move the method you need to call into a static util method and pass in any fields (usually a persistence field) you need to keep the logic the same.

Here's an example:

```
public class MyStaticUtil {
    public static void sharedLogicFromTwoLocalServices(APersistence p1, BPersistence p2, ...) {
        // shared logic that both services need.
    }
}
```

Both local services can reference both persistences and not cause any circular dependencies.

**Pull request closed without merging**
