### PR TITLE
LPS-68408 Add error message in case of wrong JVM configuration

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hey Preston,

This is a fix we discussed a couple weeks ago. Let me know what you think.

Thanks.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
@jonathanmccann maybe these should be extracted into a separate startup action instead of modifying MainServlet.  What do you think?

**Comment by jonathanmccann** [comment]
We could. Seems like it goes along with the patching level, but it might be cleaner to separate it out.

/cc @jorgediaz-lr

**Comment by jonathanmccann** [comment]
Also, not sure why the local source formatter didn't catch that error.

**Comment by Preston-Crary** [comment]
Yeah, I guess it makes sense to put it there.  Just trying to consider other options.

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
https://github.com/Preston-Crary/liferay-portal/pull/189

**Pull request closed without merging**
