### PR TITLE
LPS-119798 Can't remove the widgets on Orphan Widgets within Change List

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by stsquared99** [comment]
@Preston-Crary Does this seem like a feasible solution? I'm not finding a problem area in the service. Tests passed here: https://github.com/stsquared99/liferay-portal/pull/173#issuecomment-881750189

**Comment by Preston-Crary** [comment]
Which method needs it for this ticket? I'm a bit nervous to add it to the whole thing since a lot of those methods call some crazy APIs.

**Comment by stsquared99** [comment]
@Preston-Crary That was my thought too. Another option is to try to get it on just the needed methods. Let me go ahead and try that right now

**Comment by Preston-Crary** [comment]
Main problem is we don't want someone deploying a portlet in CT mode. Some of the methods might be okay to call though.

**Pull request closed without merging**
