### PR TITLE
LPS-99052 processUser resource integration tests added

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
Hey @Preston-Crary 

This one contains the changes of https://github.com/Preston-Crary/liferay-portal/pull/815 as it is depending on that.

Thanks,
Zoli

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test:change-tracking

**Comment by Preston-Crary** [comment]
Hi @zoltancsaszi,

we're working on moving away from using soy + rest services for the UI.  We also have plans to refactor the searching logic.  We want to hold off on adding more tests for the current code base until we have the new system in place.

Sorry you spent time on this.

**Pull request closed without merging**
