### PR TITLE
LPS-120626

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
ci:test:backend-hypersonic

**Comment by Preston-Crary** [comment]
ci:test:backend-hypersonic

**Comment by Preston-Crary** [comment]
ci:test:backend-hypersonic

**Comment by Preston-Crary** [comment]
ci:test:backend-hypersonic

**Comment by Preston-Crary** [comment]
Hi @vicnate5, can you check the last test run against upstream?

**Comment by vicnate5** [comment]
@Preston-Crary No unique failures.

**Comment by Preston-Crary** [comment]
https://github.com/shuyangzhou/liferay-portal/pull/9433

**Pull request closed without merging**
