### PR TITLE
LPS-123199

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-123199

Sending as follow-up to https://github.com/Preston-Crary/liferay-portal/pull/1243

Answering your comments:

- https://github.com/Preston-Crary/liferay-portal/pull/1243#pullrequestreview-526494190 - Done, see https://github.com/Preston-Crary/liferay-portal/commit/895d8687efb9eb5a57351acfb3c70255e3f7b397

- https://github.com/Preston-Crary/liferay-portal/pull/1243#pullrequestreview-526495236 - Done, see https://github.com/Preston-Crary/liferay-portal/commit/895d8687efb9eb5a57351acfb3c70255e3f7b397

- https://github.com/Preston-Crary/liferay-portal/pull/1243#pullrequestreview-526496200 - If we haven't modified a given layout's priority, then we shouldn't need to ensure it's priority meshes with it's siblings, unless they have their priority modified.  If this is the case, then we are still good because we have added it's parent to the list.

- https://github.com/Preston-Crary/liferay-portal/pull/1243#pullrequestreview-526498833 - See https://github.com/Preston-Crary/liferay-portal/commit/d79b1a65378370f7e11d6f3124e71d2c32a3f12a and https://github.com/Preston-Crary/liferay-portal/commit/71508ab0453b831e6ee65636ce93bdf790b362bf.  The solution is to allow for an upper-limit of returned results - or more importantly - fetches.  There is now a limit set everywhere it is safe to do so.  The only call which we no longer set a limit is [RecentSitesItemSelectorViewDisplayContext.getGroupSearch()](https://github.com/liferay/liferay-portal/blob/master/modules/apps/site/site-item-selector-web/src/main/java/com/liferay/site/item/selector/web/internal/display/context/RecentSitesItemSelectorViewDisplayContext.java#L73-L92).  This method should return all results, since the "total" value is used and page pagination can occur.

Please let me know if you have any other questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
These are solving 2 separate performance problems. Please split this into 2 tickets. One ticket for 895d868 and e25edea. Another ticket for the other commits - that way if something breaks we have a smaller ticket to look at.

For the recent site changes you deprecated the method but pointed out a usage you left behind in RecentSitesItemSelectorViewDisplayContext.getGroupSearch(). If that's still needed we shouldn't deprecate the method.

We should add an upper bound on the number of recent groupIds we allow. How "recent" can it be if it's 100+ sites ago? If you don't want to pick the number then make a configuration for it. That whole API class seems weird, so that's another reason why I think we should separate these 2 issues.

**Comment by ChrisKian** [comment]
First follow-up PR: https://github.com/Preston-Crary/liferay-portal/pull/1251

**Comment by ChrisKian** [comment]
Second follow-up PR send to https://github.com/liferay-echo/liferay-portal/pull/2884

**Pull request closed without merging**
