### PR TITLE
LPS-84861 create copy permission API in Journal service, build service

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by arthurchan35** [comment]
@Preston-Crary ,
This PR contains two tickets:
LPS-84860 and LPS-84861, both are sub tasks of LPS-84801

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
Please see https://github.com/arthurchan35/liferay-portal/pull/24

**Pull request closed without merging**
