### PR TITLE
[TS] LPS-74272 URLs are not well generated when locale.prepend.friendly.url.style=2

### PR DESCRIPTION
**Pull request by dacousalr**
Hi @Preston-Crary,

I have addressed [your previous concerns](https://github.com/Preston-Crary/liferay-portal/pull/466#issuecomment-355630741):
- new cases are tested within the method testCanonicalURL instead of creating new test methods
- unnecessary adaptations to test classes have been suppressed since LPS-74272 does not have LPS-74031's scope

Please, let me know if any additional information is needed for your review.

Best,
Daniel

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by dacousalr** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
@dacousalr sorry, for the delay.  I should be able to make time to look at this sometime this week.

**Comment by Preston-Crary** [comment]
@dacousalr I reworded your commit messages to include the ticket number. Please make sure you have the ticket number at the beginning of your commit messages.

Please see https://github.com/shuyangzhou/liferay-portal/pull/5552

**Comment by dacousalr** [comment]
Thanks @Preston-Crary for your review and the heads-up.

**Pull request closed without merging**
