### PR TITLE
LPS-135504 more conflicts rebased w/ qualifiers

### PR DESCRIPTION
**Pull request by ctang3**
Squashed commits for the conflicting keys for this PR. One's from the previous already-merged PR are in individual commits.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
@ctang3 can you run gw baseline in each of the -api modules? You can use `git log --name-only --oneline` to easily see which ones you touched.

**Comment by ctang3** [comment]
@Preston-Crary pushed the versioning commit, thanks

**Comment by Preston-Crary** [comment]
ci:stop

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by ctang3** [comment]
ci:stop

**Comment by ctang3** [comment]
Brian Wulbern was reviewing some translation changes and noticed that a few of the translated files in `portal-store-gcs` were referencing S3 instead of GCS in the keys' values when he was looking at [this commit from my previous PR](https://github.com/liferay/liferay-portal/commit/16dcbe304a598e9d8b329bf0caaa8554e0da26a2#diff-8bbb179910d053423608b6e8751683941b14cbb1b0b4f1f11a1240593c19a507R23). I added a fix [[0399d2e](https://github.com/Preston-Crary/liferay-portal/pull/1465/commits/0399d2ef23f6c357f5ec47b3ccef40461c741419)] for that to this PR since it's about to go out.

**Comment by ctang3** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
ci:reevaluate:1307401_339

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
@vicnate5 can you check this one and forward to Brian if it's safe, thanks!

**Comment by vicnate5** [comment]
@Preston-Crary @ctang3 The semver failure is real from https://github.com/Preston-Crary/liferay-portal/pull/1465/commits/7dbae9fd3ec52e6ba22365113a9fa25838c99027
```
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec]   com.liferay.portal.kernel.model                    UNCHANGED  6.4.0      6.3.0      6.3.0      EXCESSIVE VERSION INCREASE
     [exec]     -   version    6.3.0
     [exec]     +   version    6.4.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/12.2.1/4ae91ebb6a7f7c072bad755978d64af480df6c71/com.liferay.portal.kernel-12.2.1.jar
```

I reproduced this locally by just fetching this branch and running `ant compile`

**Comment by ctang3** [comment]
@Preston-Crary @vicnate5 I just pushed a reversion for that semver change

**Comment by vicnate5** [comment]
ci:forward

**Comment by vicnate5** [comment]
Manually Forwarded
https://github.com/brianchandotcom/liferay-portal/pull/106009

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
