### PR TITLE
LPS-79309

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-79309

After testing some more, I found the URL issue I was experiencing was only because I had different friendlyURLs for each translated page, but I was only changing the locale code, not the friendlyURL.  When I also updated the friendlyURL or used pages without distinct friendlyURLs, everything works as it should.

Let me know if you have any questions.  Thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test

**Comment by Preston-Crary** [comment]
@ChrisKian can you add a test case to I18nServletTest?  If it's easier to test you can move it to the site-test module.

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
I18nServletTest has some test failures. Can you run update the test with the new test case, fix the test failures and resend?

Thanks!

**Comment by ChrisKian** [comment]
See https://github.com/Preston-Crary/liferay-portal/pull/533

**Pull request closed without merging**
