### PR TITLE
LPS-118935 BaseCTDisplayRenderer

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
@xbrianlee can you check the functional test failure? Thanks!

**Comment by xbrianlee** [comment]
@Preston-Crary The functional failures are unrelated. They're all actually failing upstream. `PagesAdmin#ViewCollectionItemViaPageFinderAndPageAdmin` is just failing less consistently.

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/92870

**Pull request closed without merging**
