### PR TITLE
LPS-107375 Delegating on DepotEntry for depot groups

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @Preston-Crary, 

We want to delegate the VIEW permission of groups with a given type (Depot) to a separate model (DepotEntry). 

These changes do what we need. 

What do you think?

Thanks!

**Comment by Preston-Crary** [comment]
Hi @4lejandrito,

can you update https://github.com/liferay/liferay-portal/blob/master/modules/apps/depot/depot-service/src/main/java/com/liferay/depot/service/impl/DepotEntryLocalServiceImpl.java#L85-L88 to also add group permissions instead?

Adding this kind of API removes any kind of control we have over the core tables and should be avoided.  Also InlineSQLHelper and search permission checker do no know about this contributor API, so making a change like this will result in very inconsistent behaviors depending on how the group is being added and filtered.

I'm not sure, but you might be duplicating efforts from the User team.  Maybe the Account stuff can be used used instead of making a system just for content repos.  @drewbrokke do you think that's possible?

**Comment by drewbrokke** [comment]
I'll have to educate myself on the problem we're trying to solve here. It certainly seems possible. Could a RoleContributor possibly work for this use-case as well?

**Comment by Preston-Crary** [comment]
It could, but using a contributor pattern never really scales that well.  If we can make it so that roles we need are included in the queries we already do, then we can save the extra queries any contributor would be making.  Group permission effect the whole system so anything we lose there has a dramatic effect on performance across the whole system.

**Comment by Preston-Crary** [comment]
Also we reduce the chance of bugs because we're not changing anything about how the system works, only the data it contains.

**Comment by 4lejandrito** [comment]
Hi @Preston-Crary,

I don't think we need to add group permissions since DepotEntry is not supposed to be a GroupedModel (it currently is, but we are thinking about changing it). It just contains a reference to its own group but it is not the same kind of relationship as in a FileEntry or a JournalArticle. Does that make sense?

I agree with your thoughts about the proposed extension point but I decided to place it there because GroupPermissionImpl already has plenty of logic that won't be used neither in the InlineSQLHelper nor in search queries. That's why I thought that was the right place for it.

Thanks!

**Comment by Preston-Crary** [comment]
> I agree with your thoughts about the proposed extension point but I decided to place it there because GroupPermissionImpl already has plenty of logic that won't be used neither in the InlineSQLHelper nor in search queries.

I'd like to remove that logic at some point :)

**Pull request closed without merging**
