### PR TITLE
LPS-98197 get dlFileEntry from database nor imported fileEntry

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
Previous PR closed: https://github.com/Preston-Crary/liferay-portal/pull/829#issuecomment-518646801

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
Hey @Preston-Crary and @4lejandrito 

I changed the code to delete the fetch and simplify as you said on https://github.com/Preston-Crary/liferay-portal/pull/828#discussion_r310715318

Check if ok.

now the only failing test is one on master (DLFileEntryIndexerIndexedFieldsTest.testIndexedFields) and it is already reported (https://issues.liferay.com/browse/LPS-99198) 

If you send Brian, remember this must not be backported, and the task it's not completed yet.

Thank you for all!

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
Hey Folks,

I see that was failing the test : 
```
com.liferay.document.library.uad.anonymizer.test.DLFolderUADAnonymizerTest.testAutoAnonymizeStatusByUserOnly
com.liferay.document.library.uad.anonymizer.test.DLFolderUADAnonymizerTest.testAutoAnonymizeUserOnly
```
So I made another push a resend the relevant tests.

I feel that the solution that we found don't go to the root cause of this problem and I feel that we will have to make patches with the time.

**Comment by Preston-Crary** [comment]
@AliciaGarciaGarcia can you resend with https://github.com/Preston-Crary/liferay-portal/pull/829 ?

**Pull request closed without merging**
