### PR TITLE
LPS-87933 InlineSQLHelperImpl doesn't honor Site Admin for multiple groupIds

### PR DESCRIPTION
**Pull request by topolik**
Hi Preston,

https://issues.liferay.com/browse/LPS-87933

Another piece to fix LPS-30938.

If you are fine with that please send to Brian.

Thanks!

### CODE REVIEW

**Comment by topolik** [comment]
ci:test

**Comment by topolik** [comment]
ci:test Cannot reproduce the test failures locally, trying another run

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
Looks like the SegmentsEntryProviderTest.testGetSegmentsEntryClassPKsWithMultipleCriterion test failure is real.

**Comment by Preston-Crary** [comment]
Please resend after fixing the test failure.  If you have questions about how to fix the test let me know.

Thanks!

**Comment by topolik** [comment]
Hi,

Thanks for the hints. Will resend, didn't get to it yet.


po 10. 12. 2018 22:56 odesílatel Nathaniel Preston Crary <
notifications@github.com> napsal:

**Comment by topolik** [comment]
Please see https://github.com/Preston-Crary/liferay-portal/pull/630. Thanks.

**Pull request closed without merging**
