### PR TITLE
LPS-122562 Extract portlet preferences XML into separate preference table

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
@vicnate5 can you double check the test results, thanks

**Comment by vicnate5** [comment]
@Preston-Crary No unique failures. Forms failed to load in the 1 poshi test, but all the other Forms tests are passing so this is a fluke.

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/96045

**Pull request closed without merging**
