### PR TITLE
LPS-118143 Separate publication management from content category in control panel

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by stsquared99** [comment]
@Preston-Crary I can separate these if you want as well.

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
No that's okay.  Just close out the other ticket after this is merged in.

**Comment by Preston-Crary** [comment]
Baseline failure, please resend thanks.

**Comment by stsquared99** [comment]
Resent: https://github.com/Preston-Crary/liferay-portal/pull/1138

**Pull request closed without merging**
