### PR TITLE
LPS-66950 build-lang

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
Does UpgradePermissionTest pass locally?

**Comment by pavel-savinov** [comment]
@Preston-Crary Yes, it passes localy, but on MySQL(here on MySQL it also works). The queries are  simple, so i really have no idea why it fails on other DBs...

**Comment by Preston-Crary** [comment]
This is why I think we should always have tests for upgrades, because otherwise we don't know what other databases are going to do.  I'm not sure why it's failing but from looking at it I see that you're not using the SQLTransformer for the bitwise logic, please see SQLTransformer._replaceBitwiseCheck.  You should use BITAND($1, $2) in the SQL so we can convert it for the various databases.

Can you setup PostgreSQL and try the upgrade there as well?  After getting it to work on two databases it'll usually work on all of them (unless it's very complex SQL).

**Pull request closed without merging**
