### PR TITLE
LPS-71009 Always ensure that the process exits so that it does not hang indefinitely

### PR DESCRIPTION
**Pull request by jonathanmccann**
Putting the System.exit inside of the caller now, looping through the available threads to see if if there are any non-daemon threads that are not named main (IE Thread-2). Please let me know if you have any questions.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
Can you clean up the code a little bit?  I think the two callables can be combined and just have a converter field.  There's also some duplication between the _generateVideoXuggler and _generateThumbnailXuggler methods that can be extracted after that change into a new private method, just pass the LiferayConverter.

**Comment by jonathanmccann** [comment]
@Preston-Crary I consolidated the logic for the _call methods, but the duplication for the _generate* methods seems a bit more tricky. We'd have to construct both a processCallable and a liferayConverter to pass to the new method, which doesn't seem to be worth removing a bit of duplication. If we made two new methods for each branch, then one method would simply be ```liferayConverter.convert``` which doesn't seem to gain much of anything either.

Let me know what you think.

**Comment by Preston-Crary** [comment]
That's fine, just wanted you to check if that was an easy change.

**Comment by jonathanmccann** [comment]
https://github.com/Preston-Crary/liferay-portal/pull/279

**Pull request closed without merging**
