### PR TITLE
Lps 83456 fix

### PR DESCRIPTION
**Pull request by arthurchan35**
Hi @Preston-Crary ,
Sorry I dont know whom should I send this pull to.

The goal with this pull is to enforce portletPreferences generation, so that no invalid combination of ownerId, ownerType and plid will be generated in portletPreferences.

Previous, portal generates portletPreferences of ownerId = 0, ownerType = 3 and plid = 0, I have resolved the issues in other sibling tickets.

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevent

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
Wasn't this to fix the old method, can we fix this without adding a new API?  Please add an integration test to show the poor behavior of the old logic that way it stays fixed and resend, thanks!

**Pull request closed without merging**
