### PR TITLE
LPS-85031 Use service builder methods instead of manual create/update

### PR DESCRIPTION
**Pull request by jkappler**
Hi @Preston-Crary, I prefer to run this through you first. It's as you mentioned last week, we should use the service builder methods in this case. I wanted to send it last week, but got caught in other stuff.

Just let me know what you think please. Thanks!

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
Hi @jkappler,

since we have the validate method call before all the calls to that private method, can't we just call this method instead of the private one?

```
updateFriendlyURLEntryLocalizations(friendlyURLEntry, urlTitleMap);
```

What do you think?

**Comment by Preston-Crary** [comment]
Maybe we would need to update the map values with the FriendlyURLNormalizerUtil.normalizeWithEncoding() method first.

**Comment by jkappler** [comment]
Hi @preston-crary, sounds good! I'll change it first thing at the office tomorrow.

Thanks!

**Comment by jkappler** [comment]
Btw, we are keeping in service builder Map<String, String> for localizations right? Brian didn't say anything about it

**Comment by Preston-Crary** [comment]
I think so, to me it makes way more sense to use what the database is using when we're passing these maps to the service.

**Comment by jkappler** [comment]
Ok!

**Pull request closed without merging**
