### PR TITLE
LPS-108805 Make it block

### PR DESCRIPTION
**Pull request by achaparro**
Hi @Preston-Crary,

We send this to you to validate this change:
https://github.com/Preston-Crary/liferay-portal/pull/994/commits/fdd8bc1380dd44c2b9b8d97a4e337ec64bc9052f

We use the LayoutLocalService in the upgrade and that one uses AssetLocalService which depends on the ViewCountManager. Our goal is to execute the upgrade once all previous classes are properly loaded otherwise ViewCountManager object in AssetLocalService will be null.

If after your review, everything is fine, please send it to Pavel to validate the logic.

Thanks!

cc/ @csierra @ricardocousolr

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by Preston-Crary** [comment]
Please see https://github.com/pavel-savinov/liferay-portal/pull/530

**Comment by Preston-Crary** [comment]
@csierra, I dropped 83acbc9 because if it can be null, it can block.  If it's blocking during an upgrade it may never become unblocked and the portal will hang forever.  Adding the reference means the fragment-service upgrade will wait until the view-count-service upgrade has run.

**Comment by csierra** [comment]
@Preston-Crary yup... that's what I was fearing and told them to check with you first.

Thx!

Carlos.

**Pull request closed without merging**
