### PR TITLE
LPS-82215 SEMVER

### PR DESCRIPTION
**Pull request by robertoDiaz**
I've updated the tests as requested.

I've also included a SEMVER update since one of the changes you introduced (the creation of a new public method in ced862526d2b188cd2f3dcc70c4498159501ef05),  requires it.

Regards.

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by robertoDiaz** [comment]
ci:test

**Comment by robertoDiaz** [comment]
ci:test

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/6381

**Pull request closed without merging**
