### PR TITLE
LPS-89176 Auto

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
Hi @Preston-Crary, Brian told me to send this to you. 

We have to add a new column to the layout table, and don't want to change all of the finders, so we use "where" to filter the system column. 

The case is that if we have an arrayable operator (such as one in G_P_P), the code is being generated incorrectly in *PersistenceImpl.java. You can check it out when searching for query.append("layout.system = [$FALSE$]"); in LayoutPersistenceImpl class. Notice that it can lead to a bad sql.

One posible, but bad solution I think, would be to specify the operator in the where attribute in the finder, but that would lead to problems in the future. 

Since this is a new case, would we need to change the templates from service builder? Or is there another workaround for this?

Thanks for the time?

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/7275

**Comment by Preston-Crary** [comment]
The ServiceBuilder is pretty old and has so many different possible combinations it's difficult to have everything covered.  If you run into any ServiceBuillder problems like this you can update the test project like in https://github.com/shuyangzhou/liferay-portal/pull/7275/commits/55afd96400cd0d23786b0c2ea1985eaef4dcf0c7, send me a pull and I'll try to resolve the issue.

Thanks

**Comment by jkappler** [comment]
Thanks @Preston-Crary!

**Pull request closed without merging**
