### PR TITLE
[TECHNICAL-SUPPORT] LPS-67452 StringUtil.splitLines(String) is inefficient

### PR DESCRIPTION
**Pull request by istvansajtos**
Hi Preston,

[LPS-67452](https://issues.liferay.com/browse/LPS-67452)

This is the continuation of [#156](https://github.com/Preston-Crary/liferay-portal/pull/156#issuecomment-244506403). First of all, sorry for the late reaction on this.

As you suggested earlier, I focused on how *words.txt* is parsed.

The measurement happened as Angelo suggested, using the scenario on [LPS-67452](https://issues.liferay.com/browse/LPS-67452) with the attached 10MB *words.txt* file. Portal was restarted among each measurement to avoid caching *words.txt*. Below you see the execution times of *isDictionaryWord* method:

**Before:** 933414ms
**After:** 128ms

However, the improvement is clearly visible with the out-of-the-box *words.txt* too:

**Before:** 2290ms
**After:** 7ms

**Note:** The last commit is a manual version update, because *buildSystemPackagesExtraManifest* didn't raise the version, however I guess it is necessary.

Please let me know if you have any questions, concerns.

Thank you,
Istvan

### CODE REVIEW

**Comment by Preston-Crary** [comment]
Hi @istvansajtos,

this looks like the right approach.  It's going to be a few days before I can review this complelely.  If there's a client waiting on this go ahead and deliver this to them as an SDH.

**Comment by Preston-Crary** [comment]
@istvansajtos Please update the LPS to reflect these changes.  The steps should be similar to what's on the LPP.

**Comment by istvansajtos** [comment]
@Preston-Crary I have removed misleading information from the LPS description. Let me know if I can do anything else.

Thank you.

**Comment by Preston-Crary** [comment]
Hi @istvansajtos,

I've sent https://github.com/shuyangzhou/liferay-portal/pull/3228 to address this issue. Doing it this way retains the caching behavior, fixes thread safety issues, ensures the resources are closed, preserves the API and fixes the performances problem by not calling StringUtil.  If you have questions about any of this let me know and I'll explain.

Thanks!

**Pull request closed without merging**
