### PR TITLE
LPS-55246 fix PMD error

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
@matethurzo, @mhan810, this is an attempt to make sure we always update the createDate and modifiedDate. I like the idea, what do you think?

**Comment by juliocamarero** [comment]
@Preston-Crary, could you please review the changes to MB? these changes seem to break 102 tests as you can see here: 				
				
https://github.com/juliocamarero/liferay-portal/pull/3376#issuecomment-98675520

thanks!

**Comment by mhan810** [comment]
Sounds good :)

Sent from my mobile device.

**Comment by matethurzo** [comment]
Yep, sounds good. We need to inform the devs after this is done, so they can make exceptions, or be aware. Thanks @Preston-Crary @juliocamarero!

**Comment by Preston-Crary** [comment]
https://github.com/juliocamarero/liferay-portal/pull/3385

**Pull request closed without merging**
