### PR TITLE
LPS-75081

### PR DESCRIPTION
**Pull request by mbowerman**

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test

**Comment by mbowerman** [comment]
ci:reopen

**Comment by mbowerman** [comment]
Should I just get rid of the CodeCoverageAssertor for that class? We can't test the escape logic in the same class.

**Comment by Preston-Crary** [comment]
That one is a unit test, you should be able to fully cover the class.  If there's something that cannot be covered we can take a look at it and consider removing that code.

**Comment by mbowerman** [comment]
Oh I see, it's because I added https://github.com/Preston-Crary/liferay-portal/pull/491/commits/eabafcf0aff10d2a6462b052c31b32af83aa1b04 without adding tests for it.

**Pull request closed without merging**
