### PR TITLE
LPS-133682 Improve review page performance for large publications

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
@xbrianlee Can you help with the functional failure steps, I'm not sure what NEXT_LINK is looking for?

CC @stsquared99

**Comment by suilin** [comment]
ci:test:bundle

**Comment by suilin** [comment]
Hi @Preston-Crary, the functional failure should be a bug, I also can reproduce it onn local.

Issue: There are no changes to display when viewing a published publications with deleted Change Type. 
1. Add a new web content
2. Enable Publications
3. Add a new publication "P1"
4. Delete the web content
5. Go to review changes
6. Assert the web content is Deleted in Web Content Article
7. Publish "P1"
8. Go to History tab
9. Click on "P1" to view the chagnes
Actual Result: There are no changes to display

/cc @xbrianlee @stsquared99

**Comment by Preston-Crary** [comment]
@stsquared99 sounds like it's related to my changes, I'm looking into this one.

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
@xbrianlee @suilin that's a really good test! This kind of thing can really only be covered by functional tests too. Pushed the fix.

**Comment by xbrianlee** [comment]
ci:forward

Last `modules-compile-jdk8` execution timed out.

**Pull request closed without merging**
