### PR TITLE
[TECHNICAL SUPPORT] LPS-69480 User with Site Member role granted via Group membership cannot access private page of an Organization Site

### PR DESCRIPTION
**Pull request by NorbertKocsis**
https://issues.liferay.com/browse/LPS-69480

### CODE REVIEW

**Comment by NorbertKocsis** [comment]
ci:reopen

**Comment by NorbertKocsis** [comment]
ci:retest

**Comment by NorbertKocsis** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
Hey @amadeafejes @NorbertKocsis, I added the test this time but next time you send me a Finder change please include a test to cover that case.

Please see my changes here:
https://github.com/brianchandotcom/liferay-portal/pull/45420

**Comment by lipusz** [comment]
Hi Preston,

Can you please document this request in Liferay Grow? It would be nice to propagate this to all teams to have more code covered by tests. :+1: Thanks!

**Pull request closed without merging**
