### PR TITLE
LPS-122164 Missing unique indexes after LPS-121714

### PR DESCRIPTION
**Pull request by achaparro**
Hi @Preston-Crary,

I think we missed to execute build services for portal after the last changes in LPS-121714. I am not sure if other modules can be affected too.

Thanks.

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:stop

**Comment by Preston-Crary** [comment]
ci:close

**Comment by Preston-Crary** [comment]
Those are  duplicates removed by LPS-121714. Bug is that service builder is adding them back.

**Pull request closed without merging**
