### PR TITLE
LPS-124362 update error message about enabling publications when staging is enabled

### PR DESCRIPTION
**Pull request by ctang3**
https://issues.liferay.com/browse/LPS-124362

### CODE REVIEW

**Comment by ctang3** [comment]
@Preston-Crary Any issues with this when you get a chance to take a look? The ticket creator asked for an update. Thanks!

**Comment by Preston-Crary** [comment]
Hi @ctang3, please rebase and I'll forward it.

**Comment by ctang3** [comment]
Rebased, thank you!

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
ci:reevaluate:1277401_15

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/107936

**Pull request closed without merging**
